import 'dotenv/config'

import { describe, expect, it } from '@jest/globals'

import * as statsQueries from '../../src/db/stats-queries.ts'

/**
 * Executes every exported stats query against the real database.
 *
 * The point is not the data — most of these return whatever the seeded test data
 * happens to produce — it is that the SQL *parses and resolves*. The camelCase migration
 * (issue #1115, phase 5) renamed 41 view names and every column reference in this
 * module through the identifier transformer, and a wrong name is a runtime error that
 * `tsc` cannot see: `schema.d.ts` is generated by converting snake -> camel, but
 * the plugin has to convert camel -> snake, and the two are not inverses.
 *
 * `stats.occurrences_per_100h_by_ac_yr` is the case that proves it. Codegen turns it
 * into `occurrencesPer100hByAcYr`, so the query builder call typechecks; the plugin
 * turns that back into `occurrences_per100h_by_ac_yr`, which does not exist. Nothing
 * short of executing the query catches that, so this suite executes all of them.
 */
describe('stats queries resolve against the database', () => {
  // Every query takes an optional filter object except these two, which require one.
  const REQUIRED_ARGS: Record<string, unknown[]> = {
    getPilotStatistics: [{ from: '2020-01-01', to: '2030-01-01' }],
    getMyStatistics: [{ memberId: 'Matti1' }],
  }

  const queries: [string, (...args: never[]) => Promise<unknown>][] = Object.entries(statsQueries)
    .filter(([name, fn]) => name.startsWith('get') && typeof fn === 'function')
    .map(([name, fn]) => [name, fn as (...args: never[]) => Promise<unknown>])

  it('exports every stats query the suite expects to cover', () => {
    // Guards against the list silently shrinking — a renamed or removed export would
    // otherwise just reduce coverage without failing anything.
    expect(queries.length).toBe(43)
  })

  it.each(queries)('%s', async (name, fn) => {
    await expect(fn(...((REQUIRED_ARGS[name] ?? []) as never[]))).resolves.toBeDefined()
  })

  // The filtered paths build different SQL from the unfiltered ones — in particular the
  // hand-written WHERE clause that getOccurrencesPerHundredHrsByAcYr needs, since it is
  // the one query that cannot go through the query builder.
  it('resolves the filtered paths too, including the raw-SQL occurrences view', async () => {
    const filters = { aircraftRegistration: 'OH-STL', yr: 2025 }

    await expect(statsQueries.getOccurrencesPerHundredHrsByAcYr(filters)).resolves.toBeDefined()
    await expect(
      statsQueries.getOccurrencesPerHundredHrsByAcYr({
        aircraftRegistration: 'OH-STL',
        yrFrom: 2020,
        yrTo: 2030,
      }),
    ).resolves.toBeDefined()
    await expect(statsQueries.getTotalFlightTimeByAcYr(filters)).resolves.toBeDefined()
    await expect(
      statsQueries.getTotalFlightTimeByAcDt({
        aircraftRegistration: 'OH-STL',
        dateFrom: '2020-01-01',
        dateTo: '2030-01-01',
      }),
    ).resolves.toBeDefined()
    await expect(
      statsQueries.getMyStatistics({
        memberId: 'Matti1',
        dateFrom: '2020-01-01',
        dateTo: '2030-01-01',
        aircraftRegistration: 'OH-STL',
      }),
    ).resolves.toBeDefined()
  })

  // The raw-SQL queries carry hand-written result types, which the plugin's result
  // transformer can quietly invalidate. These assert the keys really are camelCase.
  it('returns camelCase keys from the raw-SQL queries', async () => {
    const occurrences = await statsQueries.getOccurrencesPerHundredHrsByAcYr()
    if (occurrences.length > 0) {
      expect(Object.keys(occurrences[0]).sort()).toEqual([
        'aircraftRegistration',
        'occurrenceCount',
        'occurrencesPer100h',
        'totalFlightMins',
        'yr',
      ])
    }

    const mine = await statsQueries.getMyStatistics({ memberId: 'Matti1' })
    expect(Object.keys(mine.totals).sort()).toEqual([
      'flightCount',
      'totalBlockMins',
      'totalFlightMins',
      'totalLandings',
      'uniqueAirports',
    ])
  })
})
