import { FlightType, type FlightLogUpsertRequest } from '../../../src/routes/flight-log/models.ts'

export const flightPayload: FlightLogUpsertRequest = {
  aircraftRegistration: 'OH-STL',
  arrivalAirport: 'EFHK',
  billingRemarks: 'N/A',
  picMemberId: 'Sanna1',
  picRole: 'FI',
  crew2MemberId: null,
  crew2Role: null,
  crew3MemberId: null,
  crew3Role: null,
  crew4MemberId: null,
  crew4Role: null,
  departureAirport: 'EFHK',
  flightType: FlightType.SCHOOL,
  fuelUpliftLitres: 40,
  fuelRemainingLitres: 20,
  incidentOrObservations: 'N/A',
  nightFlyingMins: 20,
  numberOfLandings: 1,
  numberOfNightLandings: 0,
  offBlockTimeEpoch: (new Date('2025-03-22T10:30:00Z').getTime() / 1000).toString(),
  takeoffTimeEpoch: (new Date('2025-03-22T10:45:00Z').getTime() / 1000).toString(),
  landingTimeEpoch: (new Date('2025-03-22T11:40:00Z').getTime() / 1000).toString(),
  onBlockTimeEpoch: (new Date('2025-03-22T11:45:00Z').getTime() / 1000).toString(),
  oilUpliftLitres: 0.2,
  personsOnBoard: 3,
  personalRemarks: 'N/A',
  totalTimeInService: 0.2,
  instrumentFlyingMins: 0,

  // admin fields
  ajlbBlankRowsBefore: 0,
  ajlbSeqNo: 1,
  billableMemberId: 'Jukka1',
  isBillableFlight: false,
  nonBillingReason: 'N/A',
  nonBillingApprovedByMemberId: 'Matti1',
  minBillableExceptionReason: null,
  minBillableExceptionApprovedByMemberId: null,
  partiallyBillableFlight: false,
  entryErrorFee: false,
  entryErrorFeeAppliedByMemberId: 'Matti1',
  validationRemarks: null,
}
