/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely'

export type AuthEventType =
  | 'login_code_expired'
  | 'login_code_invalid'
  | 'login_code_max_attempts'
  | 'login_failed'
  | 'login_success'
  | 'logout'
  | 'passkey_login_failed'
  | 'passkey_login_success'
  | 'passkey_registered'
  | 'passkey_removed'
  | 'registration_verified'
  | 'token_refresh'

export type BookingStatus = 'CANCELLED' | 'CONFIRMED' | 'TENTATIVE'

export type BookingType = 'CROSSCOUNTRY' | 'MAINTENANCE' | 'PRACTICE' | 'PRIVATE' | 'TRAINING'

export type CancellationReason =
  | 'AIRCRAFT_TECHNICAL'
  | 'IM_SAFE_CHECKLIST'
  | 'OTHER'
  | 'PERSONAL_CONFLICT'
  | 'PREFER_NOT_DISCLOSE'
  | 'WEATHER_DEPARTURE'
  | 'WEATHER_DESTINATION'
  | 'WEATHER_ENROUTE'

export type CrewRole = 'FE' | 'FI' | 'OBS' | 'PIC' | 'STU'

export type DtoItemOutcome = 'COMPLETED' | 'FAILED' | 'MOVED_TO_HIL'

export type DtoSyllabusStatus = 'ARCHIVED' | 'DRAFT' | 'PUBLISHED' | 'WAITING_FOR_APPROVAL'

export type DtoVerificationResult = 'APPROVED' | 'FAILED'

export type ExamAttemptStatus = 'ABANDONED' | 'GRADED' | 'IN_PROGRESS' | 'SUBMITTED'

export type ExamExamType = 'AFM' | 'DTO' | 'OTHER' | 'SELF_STUDY'

export type ExamExamVersionStatus = 'DRAFT' | 'PUBLISHED' | 'RETIRED'

export type Feeprocessstatus = 'inProgress' | 'processed'

export type FeeType = 'annual_fee' | 'equipment_fee'

export type FlightAircraftDocumentType =
  | 'ARC'
  | 'Certificate of Airworthiness'
  | 'Checklist'
  | 'Finavia Season card'
  | 'Insurance Certificate'
  | 'Maintenance Manual'
  | 'Noise Certificate'
  | 'Other'
  | 'POH / AFM'
  | 'Radio Licence'
  | 'Registration'
  | 'Transponder Mode S certificate'
  | 'Weight Report'

export type FlightDefectStatus = 'ACTIVE' | 'MOVED_TO_HIL' | 'RESOLVED'

export type FlightLogStatus = 'INVOICED' | 'NEW' | 'PAID' | 'QUEUED_FOR_INVOICING' | 'VALIDATED'

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>

export type InventoryItemCondition = 'FAIR' | 'GOOD' | 'POOR' | 'UNKNOWN'

export type InventoryItemType = 'ASSET' | 'CONSUMABLE'

export type InvoiceType =
  | 'ANNUAL_FEE'
  | 'CREDIT_NOTE'
  | 'EQUIPMENT_FEE'
  | 'FLIGHT'
  | 'INSTRUCTION'
  | 'JOINING_FEE'
  | 'MISC'
  | 'SHOP_ORDER'

export type Json = JsonValue

export type JsonArray = JsonValue[]

export type JsonObject = {
  [x: string]: JsonValue | undefined
}

export type JsonPrimitive = boolean | number | string | null

export type JsonValue = JsonArray | JsonObject | JsonPrimitive

export type MemberType =
  'EXTERNAL' | 'FLYING' | 'HONORARY' | 'JUNIOR' | 'NON-FLYING' | 'REMOVED' | 'SYSTEM'

export type MikLang = 'en' | 'fi' | 'sv'

export type NonRenewalActionType = 'MEMBERSHIP_CANCELLED' | 'REMINDER_SENT'

export type Numeric = ColumnType<number, number | string, number | string>

export type Occurrencestatus =
  'ANONYMIZED' | 'ANONYMIZING' | 'CLOSED' | 'DELETED' | 'NEW' | 'PROCESSED' | 'RECEIVED'

export type SecretClassType = 'BOARD' | 'MEMBER'

export type ShopOrderStatus = 'CANCELLED' | 'INVOICED' | 'PENDING' | 'PROCESSING' | 'REFUNDED'

export type ShopProductType = 'FLIGHT_HOURS_PACKAGE' | 'STANDARD'

export type SimplbooksOutboxStatus = 'FAILED' | 'PENDING' | 'PROCESSING' | 'SKIPPED' | 'SYNCED'

export type Timestamp = ColumnType<Date, Date | string, Date | string>

export interface AcctsAircraftPricing {
  created_at: Generated<Timestamp>
  created_by: string | null
  notes: string | null
  price_per_min: Numeric
  registration: string
  updated_at: Generated<Timestamp | null>
  updated_by: string | null
  valid_from: string
  valid_to: string | null
}

export interface AcctsCostCentre {
  code: string
  description: string
}

export interface AcctsExpenseCategory {
  active: Generated<boolean>
  code: string
  id: Generated<number>
  label_en: string
  label_fi: string
  label_sv: string
  requires_aircraft: Generated<boolean>
  requires_flight: Generated<boolean>
}

export interface AcctsExpenseClaim {
  aircraft_id: string | null
  approved_at: Timestamp | null
  approved_by: string | null
  category_id: number
  ccy: Generated<string>
  created_at: Generated<Timestamp>
  description: string | null
  expense_date: string | null
  flight_log_id: string | null
  fuel_litres: Numeric | null
  fuel_type: string | null
  fx_rate: Numeric | null
  iban: string | null
  iban_account_name: string | null
  id: Generated<string>
  member_id: string
  receipt_file_name: string | null
  receipt_file_size: Int8 | null
  receipt_mime_type: string | null
  receipt_storage_key: string | null
  receipt_uploaded_at: Timestamp | null
  rejected_at: Timestamp | null
  rejected_by: string | null
  rejection_reason: string | null
  simplbooks_purchase_id: Int8 | null
  status: Generated<string>
  submitted_at: Timestamp | null
  title: string
  updated_at: Generated<Timestamp>
}

export interface AcctsExpenseClaimLineItem {
  claim_id: string
  cost_centre_code: string | null
  description: string
  fuel_type: string | null
  id: Generated<number>
  item_id: number | null
  quantity: Generated<Numeric>
  sort_order: Generated<number>
  unit: Generated<string>
  unit_price: Numeric
}

export interface AcctsExpenseClaimMessage {
  body: string
  claim_id: string
  id: Generated<number>
  message_type: string
  sender_id: string
  sent_at: Generated<Timestamp>
}

export interface AcctsExpenseMileageDetail {
  /**
   * True when the journey exceeded the km soft-limit and board approval has been confirmed
   */
  board_approved: Generated<boolean>
  claim_id: string
  created_at: Generated<Timestamp>
  distance_km: Numeric
  /**
   * AES-256-GCM encrypted Finnish social security number (HETU) — GDPR sensitive
   */
  hetu_encrypted: string | null
  id: Generated<number>
  /**
   * Date of the journey
   */
  journey_date: string
  /**
   * Effective rate at time of claim creation (rate_per_km * (1 - discount_pct/100))
   */
  rate_per_km: Numeric
  /**
   * Free-text route description, e.g. "Helsinki - Tampere - Helsinki"
   */
  route: string
  updated_at: Generated<Timestamp>
}

export interface AcctsInvoice {
  created_at: Generated<Timestamp>
  created_by: string
  currency: Generated<string>
  description: string | null
  due_at: string
  id: Int8
  invoice_type: InvoiceType
  is_paid: Generated<boolean>
  member_id: string
  overdue_email_sent_at: Timestamp | null
  paid_at: string | null
  pmt_ref: string
  sent_at: string | null
  total_sum: Numeric | null
  updated_at: Generated<Timestamp>
  updated_by: string
}

export interface AcctsItems {
  code: string
  expense_claim_item: Generated<boolean>
  id: number
  item: Json | null
  name: string
}

export interface AcctsMileageAllowance {
  created_at: Generated<Timestamp>
  created_by: string
  /**
   * Percentage of the official rate that the club actually pays (default 50%)
   */
  discount_pct: Generated<Numeric>
  id: Generated<number>
  /**
   * Official rate €/km as published by the Finnish Tax Administration
   */
  rate_per_km: Numeric
  tax_year: number
  updated_at: Generated<Timestamp>
  updated_by: string
}

export interface AcctsOutboxSimplbooks {
  created_at_utc: Generated<Timestamp>
  error_message: string | null
  event_type: string
  id: string
  payload: Json
  processed_at: Timestamp | null
  status: Generated<SimplbooksOutboxStatus>
  updated_at_utc: Generated<Timestamp>
}

export interface AcctsRecurringFeesProcessing {
  created_at: Generated<Timestamp>
  created_by: string
  fee_type: FeeType
  status: Feeprocessstatus
  updated_at: Generated<Timestamp>
  updated_by: string
  year: number
}

export interface DtoFlightItemOutcomes {
  attempt_id: string
  created_at: Generated<Timestamp>
  item_id: string
  outcome: DtoItemOutcome
  remarks: string | null
  updated_at: Generated<Timestamp>
}

export interface DtoHilQueue {
  hil_id: Generated<string>
  item_id: string
  member_id: string
  notes: string | null
  opened_at: Generated<Timestamp>
  opened_on_attempt_id: string
  resolution_outcome: DtoItemOutcome | null
  resolved_at: Timestamp | null
  resolved_on_attempt_id: string | null
  syllabus_id: string
}

export interface DtoMemberSyllabus {
  assigned_at: Generated<Timestamp>
  assigned_by: string
  deactivated_at: Timestamp | null
  is_active: Generated<boolean>
  member_id: string
  member_syllabus_id: Generated<string>
  syllabus_id: string
}

export interface DtoSyllabus {
  created_at: Generated<Timestamp>
  created_by: string
  description: string | null
  major_version: number
  min_block_time_mins: number | null
  minor_version: number
  patch_version: Generated<number>
  program_id: string
  published_at: Timestamp | null
  status: Generated<DtoSyllabusStatus>
  syllabus_id: Generated<string>
  updated_at: Generated<Timestamp>
  updated_by: string
  version: Generated<string | null>
}

export interface DtoSyllabusFlightAttempts {
  attempt_id: Generated<string>
  created_at: Generated<Timestamp>
  flight_log_id: string
  instructor_comments: string | null
  instructor_member_id: string
  member_syllabus_id: string
  requires_reverification: Generated<boolean>
  syllabus_flight_id: string
  updated_at: Generated<Timestamp>
  verification_result: DtoVerificationResult | null
  verified_at: Timestamp | null
  verified_by: string | null
}

export interface DtoSyllabusFlightItems {
  description: string | null
  item_id: Generated<string>
  mandatory: Generated<boolean>
  name: string
  sort_order: number
  syllabus_flight_id: string
}

export interface DtoSyllabusFlights {
  code: string
  created_at: Generated<Timestamp>
  description: string | null
  flight_id: Generated<string>
  is_interim_checkpoint: Generated<boolean>
  name: string
  recommended_block_time_mins: number | null
  sort_order: number
  syllabus_id: string
  tags: Generated<string[]>
  updated_at: Generated<Timestamp>
}

export interface DtoTrainingProgram {
  created_at: Generated<Timestamp>
  created_by: string
  description: string | null
  name: string
  program_id: Generated<string>
  updated_at: Generated<Timestamp>
  updated_by: string
}

export interface EmtMessages {
  created: Generated<Timestamp>
  global_position: Generated<Int8 | null>
  is_archived: Generated<boolean>
  message_data: Json
  message_id: string
  message_kind: Generated<string>
  message_metadata: Json
  message_schema_version: string
  message_type: string
  partition: Generated<string>
  stream_id: string
  stream_position: Int8
  transaction_id: string
}

export interface EmtProcessors {
  created_at: Generated<Timestamp>
  last_processed_checkpoint: string
  last_processed_transaction_id: string
  last_updated: Generated<Timestamp>
  partition: Generated<string>
  processor_id: string
  processor_instance_id: Generated<string | null>
  status: Generated<string>
  version: Generated<number>
}

export interface EmtProjections {
  created_at: Generated<Timestamp>
  definition: Generated<Json>
  kind: string
  last_updated: Generated<Timestamp>
  name: string
  partition: Generated<string>
  status: string
  type: string
  version: Generated<number>
}

export interface EmtStreams {
  is_archived: Generated<boolean>
  partition: Generated<string>
  stream_id: string
  stream_metadata: Json
  stream_position: Int8
  stream_type: string
}

export interface ExamAttemptAnswers {
  attempt_id: string
  choice_id: string | null
  created_at: Generated<Timestamp>
  question_id: string
  updated_at: Generated<Timestamp>
}

export interface ExamAttemptQuestions {
  attempt_id: string
  question_id: string
  sort_order: Generated<number>
}

export interface ExamAttempts {
  abandon_reason: string | null
  abandoned_at: Timestamp | null
  attempt_id: string
  correct_count: number | null
  created_at: Generated<Timestamp>
  graded_at: Timestamp | null
  language: Generated<string>
  member_id: string
  passed: boolean | null
  score_percent: Numeric | null
  status: Generated<ExamAttemptStatus>
  submitted_at: Timestamp | null
  total_count: number | null
  updated_at: Generated<Timestamp>
  version_id: string
}

export interface ExamChoices {
  choice_id: string
  is_correct: Generated<boolean>
  question_id: string
  sort_order: Generated<number>
}

export interface ExamChoiceTranslations {
  choice_id: string
  language: string
  text: string
}

export interface ExamExams {
  created_at: Generated<Timestamp>
  created_by: string
  exam_id: string
  exam_type: Generated<ExamExamType>
  name: string
  updated_at: Generated<Timestamp>
  updated_by: string
}

export interface ExamExamVersions {
  created_at: Generated<Timestamp>
  created_by: string
  default_language: Generated<string>
  exam_id: string
  pass_percent: Generated<Numeric>
  /**
   * When set, each attempt draws this many randomly-selected questions from the version pool. NULL means all questions are used.
   */
  question_count: number | null
  status: Generated<ExamExamVersionStatus>
  supported_languages: Generated<string[]>
  updated_at: Generated<Timestamp>
  updated_by: string
  version_id: string
  version_number: Generated<number>
}

export interface ExamExamVersionTranslations {
  description: string | null
  language: string
  title: string
  version_id: string
}

export interface ExamQuestions {
  question_id: string
  sort_order: Generated<number>
  version_id: string
}

export interface ExamQuestionTranslations {
  language: string
  prompt: string
  question_id: string
  reasoning: string | null
}

export interface FlightAircraft {
  active: Generated<boolean>
  created_at: Generated<Timestamp>
  created_by: string
  display_name: string
  equipment: string | null
  fuel_types: string[]
  hidden: Generated<boolean>
  image_url: string | null
  last_maintenance_date: string
  last_maintenance_mins: number
  last_maintenance_type: string
  location: string | null
  maintenance_cycle: number
  manufacturer: string
  model: string
  next_maintenance_date: string | null
  next_maintenance_mins: number
  next_maintenance_type: string
  notes: Json | null
  preferred_fuel_type: string | null
  registration: string
  reserved_hours: number
  seats: number
  total_percentage_hours: number
  updated_at: Generated<Timestamp>
  updated_by: string
  usable_fuel_litres: number
  year_of_manufacture: number
}

export interface FlightAircraftCards {
  aircraft_registration: string
  card_id: Generated<number>
  created_at: Generated<Timestamp>
  created_by: string
  description: string | null
  name: string
  updated_at: Generated<Timestamp>
  updated_by: string
  valid_from: string | null
  valid_to: string | null
}

export interface FlightAircraftDocumentExpiryNotifications {
  days_threshold: Generated<number>
  document_id: number
  id: Generated<number>
  notification_type: string
  sent_at: Generated<Timestamp>
}

export interface FlightAircraftDocumentsFiles {
  aircraft_registration: string
  created_at: Generated<Timestamp>
  created_by: string
  description: string | null
  document_id: Generated<number>
  document_type: FlightAircraftDocumentType
  document_url: string
  file_name: string
  file_size: number | null
  is_active: Generated<boolean>
  mime_type: string | null
  storage_key: string | null
  title: string
  updated_at: Generated<Timestamp>
  updated_by: string
  valid_from: string | null
  valid_to: string | null
}

export interface FlightAircraftHil {
  aircraft_registration: string
  created_at: Generated<Timestamp>
  created_by: string
  defect_cat: string
  description: string
  due_date: Timestamp
  hil_id: Generated<string>
  hil_number: number
  name: string
  open_date: Timestamp
  resolved_note_id: string | null
  source_ref: string
  updated_at: Generated<Timestamp>
  updated_by: string
}

export interface FlightAircraftHilAudit {
  audit_id: Generated<number>
  changed_at: Generated<Timestamp>
  changed_by: string
  changed_data: Json | null
  hil_id: string
  new_data: Json | null
  operation_type: string
}

export interface FlightAircraftHilExtension {
  created_at: Generated<Timestamp>
  created_by: string
  extension_date: Timestamp
  extension_due: Timestamp
  extension_id: Generated<string>
  hil_id: string
  name: string
}

export interface FlightAircraftHilExtensionAudit {
  audit_id: Generated<number>
  changed_at: Generated<Timestamp>
  changed_by: string
  changed_data: Json | null
  extension_id: string
  new_data: Json | null
  operation_type: string
}

export interface FlightAircraftJourneyLogBook {
  aircraft_registration: string
  created_at: Generated<Timestamp>
  created_by: string
  end_date: string | null
  no_of_pages: number
  rows_per_page: number
  seq_no: number
  start_date: string
  start_flight_mins: number
  start_flight_time: Generated<string>
  start_landings: Generated<number>
  start_page: number
  updated_at: Generated<Timestamp>
  updated_by: string
}

export interface FlightAircraftLandingsBaseline {
  aircraft_registration: string
  baseline_landings: number
  created_at: Generated<Timestamp>
  created_by: string | null
  updated_at: Generated<Timestamp>
  updated_by: string | null
}

export interface FlightAircraftNavdata {
  aircraft_registration: string
  created_at: Generated<Timestamp>
  created_by: string
  cycle: string
  expires: string
  navdata_id: Generated<string>
  update_date: string
  updater_member_id: string
}

export interface FlightDefect {
  aircraft_registration: string
  ajlb_seq_no: number
  blank_rows_after: Generated<number>
  created_at: Generated<Timestamp>
  created_by: string
  defect_id: Generated<string>
  description: string
  flight_id: string | null
  flight_mins: number
  hil_id: string | null
  resolved_note_id: string | null
  status: Generated<FlightDefectStatus>
  updated_at: Generated<Timestamp>
  updated_by: string
}

export interface FlightDefectAudit {
  audit_id: Generated<number>
  changed_at: Generated<Timestamp>
  changed_by: string
  changed_data: Json | null
  defect_id: string
  new_data: Json | null
  operation_type: string
}

export interface FlightFlightCredits {
  allocated_by_member_id: string
  created_at: Generated<Timestamp>
  credited_mins: number
  flight_id: string
  note: string | null
  updated_at: Generated<Timestamp>
}

export interface FlightFuelTypes {
  name: string
  sort_order: Generated<number>
}

export interface FlightLogs {
  aircraft_registration: string
  ajlb_blank_rows_before: number
  ajlb_page_number: number | null
  ajlb_row_number: number | null
  ajlb_seq_no: number
  ajlb_total_flight_mins: number | null
  ajlb_total_flight_time: Generated<string | null>
  ajlb_total_landings: number | null
  arrival_airport: string
  billable_member_id: string
  billing_remarks: string | null
  block_mins: Generated<number>
  block_time: Generated<string>
  created_at: Generated<Timestamp>
  created_by: string
  crew2_last_name: string | null
  crew2_member_id: Generated<string | null>
  crew2_role: CrewRole | null
  crew3_last_name: string | null
  crew3_member_id: Generated<string | null>
  crew3_role: CrewRole | null
  crew4_last_name: string | null
  crew4_member_id: Generated<string | null>
  crew4_role: CrewRole | null
  departure_airport: string
  entry_error_fee: Generated<boolean>
  entry_error_fee_applied_by_member_id: string | null
  flight_id: string
  flight_mins: Generated<number>
  flight_time: Generated<string>
  flight_type: string
  fuel_remaining_litres: Numeric
  fuel_uplift_litres: Numeric | null
  incident_or_observations: string | null
  instrument_flying_mins: number
  invoice_number: Generated<string | null>
  is_billable_flight: boolean
  is_billed: Generated<boolean>
  is_dto_training_flight: boolean
  landing_time_epoch: Int8
  landing_time_utc: Generated<Timestamp>
  min_billable_exception_approved_by_member_id: string | null
  min_billable_exception_reason: string | null
  night_flying_mins: number
  non_billing_approved_by_member_id: string | null
  non_billing_reason: string | null
  number_of_landings: number
  number_of_night_landings: Generated<number>
  off_block_time_epoch: Int8
  off_block_time_utc: Generated<Timestamp>
  oil_uplift_litres: Numeric | null
  on_block_time_epoch: Int8
  on_block_time_utc: Generated<Timestamp>
  partially_billable_flight: Generated<boolean>
  personal_remarks: string | null
  persons_on_board: number
  pic_last_name: string
  pic_member_id: string
  pic_role: CrewRole
  priv_or_com_flight: string
  status: Generated<FlightLogStatus>
  takeoff_time_epoch: Int8
  takeoff_time_utc: Generated<Timestamp>
  total_time_in_service: Numeric | null
  updated_at: Generated<Timestamp>
  updated_by: string
  validation_remarks: string | null
}

export interface FlightLogsAudit {
  audit_id: Generated<number>
  changed_at: Generated<Timestamp>
  changed_by: string
  changed_data: Json | null
  flight_id: string
  new_data: Json | null
  operation_type: string
}

export interface FlightMaintenanceNote {
  aircraft_registration: string
  ajlb_seq_no: number
  blank_rows_after: Generated<number>
  created_at: Generated<Timestamp>
  created_by: string
  description: string
  flight_mins: number
  hil_id: string | null
  note_id: Generated<string>
  performed_by: string
  updated_at: Generated<Timestamp>
  updated_by: Generated<string>
}

export interface FlightMaintenanceNoteAudit {
  audit_id: Generated<number>
  changed_at: Generated<Timestamp>
  changed_by: string
  changed_data: Json | null
  new_data: Json | null
  note_id: string
  operation_type: string
}

export interface FlightOccurrenceAccess {
  access_id: Generated<number>
  author: Generated<boolean>
  manage_access: Generated<boolean>
  member_id: string | null
  report_id: string
  role_id: string | null
  updated_at: Generated<Timestamp>
  updated_by: string
  write_access: Generated<boolean>
}

export interface FlightOccurrences {
  animal_number: string | null
  animal_size: string | null
  animal_species: string | null
  arrival_airport: string | null
  categories: Json
  comments: Generated<Json>
  created_at: Generated<Timestamp>
  created_by: string
  dead_line: Timestamp | null
  departure_airport: string | null
  description: string
  handling: Generated<Json>
  headline: string
  is_dto_report: boolean
  is_weather_relevant: boolean | null
  linked_report_id: string | null
  location: string
  occurrence_date: Timestamp
  processed_date: Timestamp | null
  registration: string | null
  report_date: Timestamp
  report_id: string
  status: Generated<Occurrencestatus>
  technical_faults: boolean | null
  updated_at: Generated<Timestamp>
  updated_by: string
}

export interface FlightVwAircraftGroundingStatus {
  open_defect_count: Int8 | null
  registration: string | null
}

export interface FlightVwFlightLogs {
  ac_total_flight_mins: number | null
  ac_total_flight_time: string | null
  ac_total_landings: number | null
  flight_id: string | null
  page_number: number | null
  row_number: number | null
}

export interface FlightVwFlightTimeTotals {
  aircraft_registration: string | null
  ajlb_seq_no: number | null
  current: boolean | null
  last_page: number | null
  new_flights_page: number | null
  sum_new_flights: number | null
  sum_new_time: string | null
  sum_validated_flights: number | null
  sum_validated_time: string | null
  total_landings: number | null
  unverified_total_flight_mins: number | null
  unverified_total_flight_time: string | null
  validated_on_block_time_utc: Timestamp | null
  validated_total_flight_mins: number | null
  validated_total_landings: number | null
  verified_total_flight_time: string | null
}

export interface FlywayDataHistory {
  checksum: number | null
  description: string
  execution_time: number
  installed_by: string
  installed_on: Generated<Timestamp>
  installed_rank: number
  script: string
  success: boolean
  type: string
  version: string | null
}

export interface FlywaySchemaHistory {
  checksum: number | null
  description: string
  execution_time: number
  installed_by: string
  installed_on: Generated<Timestamp>
  installed_rank: number
  script: string
  success: boolean
  type: string
  version: string | null
}

export interface FuelPricesContent {
  created_at: Generated<Timestamp>
  created_by: string
  id: number
  markdown: Generated<string>
  updated_at: Generated<Timestamp>
  updated_by: string
}

export interface InventoryAuditLog {
  change_type: string
  created_at: Generated<Timestamp>
  item_id: string
  log_id: Generated<number>
  member_id: string
  new_value: Json | null
  notes: string | null
  old_value: Json | null
}

export interface InventoryCategories {
  category_id: string
  created_at: Generated<Timestamp>
  created_by: string
  description: Json | null
  is_active: Generated<boolean>
  name: Json
  sort_order: Generated<number>
  updated_at: Generated<Timestamp>
  updated_by: string
}

export interface InventoryItems {
  category_id: string
  condition: Generated<InventoryItemCondition>
  created_at: Generated<Timestamp>
  created_by: string
  description: Json | null
  image_url: string | null
  is_active: Generated<boolean>
  item_id: string
  item_type: Generated<InventoryItemType>
  location_id: string | null
  low_stock_threshold: number | null
  name: Json
  notes: string | null
  quantity: Generated<number>
  serial_number: string | null
  tags: Generated<string[]>
  updated_at: Generated<Timestamp>
  updated_by: string
}

export interface InventoryLocations {
  created_at: Generated<Timestamp>
  created_by: string
  description: Json | null
  is_active: Generated<boolean>
  location_id: string
  name: Json
  sort_order: Generated<number>
  updated_at: Generated<Timestamp>
  updated_by: string
}

export interface MemberAnnualFees {
  created_at: Generated<Timestamp>
  created_by: string
  fee_type: FeeType
  invoice_id: number
  member_id: string
  updated_at: Generated<Timestamp>
  updated_by: string
  year: number
}

export interface MemberBrevoSyncState {
  created_at: Generated<Timestamp>
  error_message: string | null
  id: Generated<number>
  last_synced_at: Generated<Timestamp>
  members_synced: Generated<number>
  sync_status: Generated<string>
}

export interface MemberDocuments {
  category: string
  created_at: Generated<Timestamp>
  created_by: string
  description: string | null
  document_id: Generated<number>
  document_url: string | null
  /**
   * Original filename of uploaded file
   */
  file_name: string | null
  /**
   * File size in bytes
   */
  file_size: number | null
  is_archived: Generated<boolean>
  is_public: Generated<boolean>
  /**
   * MIME type of uploaded file
   */
  mime_type: string | null
  published_date: Generated<string>
  /**
   * Storage key for Digital Ocean Spaces
   */
  storage_key: string | null
  tags: string[] | null
  title: string
  updated_at: Generated<Timestamp>
  updated_by: string
}

export interface MemberDocumentTinyUrls {
  access_count: Generated<number>
  aircraft_document_id: number | null
  created_at: Generated<Timestamp>
  created_by: string
  document_id: number | null
  document_type: string
  expires_at: Timestamp
  last_accessed_at: Timestamp | null
  short_code: string
  url: string
}

export interface MemberEvents {
  created_at: Generated<Timestamp>
  created_by: string
  description: string | null
  end_time: Timestamp
  event_id: Generated<string>
  is_public: Generated<boolean>
  location: string | null
  start_time: Timestamp
  title: string
  updated_at: Generated<Timestamp>
  updated_by: string
}

export interface MemberLoginAttempts {
  code_hash: string
  created_at: Generated<Timestamp>
  email: string
  expires_at: Timestamp
  failed_attempts: Generated<number>
  id: Generated<string>
  ip_address: string | null
  link_token_hash: string | null
  used_at: Timestamp | null
}

export interface MemberLoginEvents {
  created_at: Generated<Timestamp>
  event_type: AuthEventType
  id: Generated<string>
  ip_address: string | null
  member_id: string | null
  user_agent: string | null
}

export interface MemberMemberToRoles {
  created_at: Generated<Timestamp>
  created_by: string
  member_id: string
  role_id: string
}

export interface MemberNonRenewalActions {
  /**
   * REMINDER_SENT = final reminder email sent; MEMBERSHIP_CANCELLED = membership deactivated
   */
  action_type: NonRenewalActionType
  id: Generated<number>
  member_id: string
  notes: string | null
  performed_at: Generated<Timestamp>
  performed_by: string
}

export interface MemberPasskeys {
  backed_up: Generated<boolean>
  counter: Generated<Int8>
  created_at: Generated<Timestamp>
  credential_id: string
  device_type: string | null
  id: Generated<string>
  last_used_at: Timestamp | null
  member_id: string
  name: string | null
  public_key: Buffer
  transports: Generated<string[]>
}

export interface MemberPendingEmailChanges {
  created_at: Generated<Timestamp>
  expires_at: Timestamp
  id: Generated<string>
  member_id: string
  new_email: string
  token_hash: string
  used_at: Timestamp | null
}

export interface MemberQualificationProofFiles {
  document_category: Generated<string>
  file_name: string
  history_id: Int8 | null
  id: Generated<number>
  member_id: string
  mime_type: string
  storage_key: string
  uploaded_at: Generated<Timestamp>
  uploaded_by: string
}

export interface MemberRegister {
  /**
   * Registration application data: flight hours, aircraft types, motivation, cover letter, declarations, etc.
   */
  application_data: Json | null
  auto_renew_annual_membership: Generated<boolean | null>
  auto_renew_equipment_fee: Generated<boolean | null>
  billing_id: string | null
  brevo_contact_id: Int8 | null
  brevo_sync_status: Generated<string | null>
  brevo_synced_at: Timestamp | null
  can_make_reservations: Generated<boolean>
  created_at: Generated<Timestamp>
  created_by: string
  /**
   * User preferences for dashboard component order and visibility. Structure: {"components": [{"id": "weather", "visible": true, "order": 0}, ...]}
   */
  dashboard_settings: Json | null
  date_of_birth: string | null
  email: string
  email_verified_at: Timestamp | null
  first_name: string
  iban: string | null
  iban_account_name: string | null
  ice_contact_name: string | null
  ice_contact_phone_number: string | null
  im_discord: string | null
  im_facebook_messenger: string | null
  im_signal: string | null
  im_telegram: string | null
  im_viber: string | null
  im_whatsapp: string | null
  is_membership_approved: Generated<boolean>
  is_membership_expired: Generated<boolean | null>
  is_training_program_pilot: Generated<boolean>
  lang_iso639: Generated<MikLang>
  last_name: string
  licence_expiry_date: string | null
  licence_id: string | null
  /**
   * Aircraft mailing list subscriptions. Structure: ["list-id-1", "list-id-2"]
   */
  mailing_lists: Json | null
  medical_class1_expiry_date: string | null
  medical_class2_expiry_date: string | null
  medical_expiry_date: string | null
  medical_lapl_expiry_date: string | null
  member_id: string
  member_since: Generated<string>
  member_type: MemberType
  membership_approved_at: Timestamp | null
  membership_approved_by: string | null
  must_update_profile: Generated<boolean>
  phone_number: string | null
  postcode: string | null
  removal_reason: string | null
  removed_at: Timestamp | null
  removed_by: string | null
  simplbooks_sync_status: Generated<string | null>
  simplbooks_synced_at: Timestamp | null
  street_address: string | null
  town_city: string | null
  updated_at: Generated<Timestamp>
  updated_by: string
}

export interface MemberRegisterAudit {
  audit_id: Generated<number>
  changed_at: Generated<Timestamp>
  changed_by: string
  changed_data: Json | null
  member_id: string
  new_data: Json | null
  operation_type: string
}

export interface MemberRoles {
  created_at: Generated<Timestamp>
  created_by: string
  description: string | null
  is_public: Generated<boolean>
  name_en: string
  name_fi: string
  name_sv: string
  permissions: Json | null
  role_id: string
  updated_at: Generated<Timestamp>
  updated_by: string
}

export interface MemberSimplbooksSyncState {
  created_at: Generated<Timestamp>
  error_message: string | null
  id: Generated<number>
  last_synced_at: Generated<Timestamp>
  members_synced: Generated<number>
  sync_status: Generated<string>
}

export interface MemberWebauthnChallenges {
  challenge: string
  created_at: Generated<Timestamp>
  email: string | null
  expires_at: Timestamp
  id: Generated<string>
  member_id: string | null
  purpose: string
}

export interface NotificationBanner {
  enabled: Generated<boolean>
  id: Generated<number>
  message: string | null
  severity: Generated<string>
  updated_at: Generated<Timestamp>
  updated_by: string | null
}

export interface PrepaidMemberPackages {
  created_at: Generated<Timestamp>
  expires_at: string
  is_expired: Generated<boolean>
  member_id: string
  member_package_id: Generated<number>
  order_id: string | null
  product_id: string
  remaining_minutes: Generated<number | null>
  total_minutes: number
  updated_at: Generated<Timestamp>
  used_minutes: Generated<number>
}

export interface PrepaidPackages {
  aircraft_registration: string
  created_at: Generated<Timestamp>
  created_by: string
  expires_at: string
  is_active: Generated<boolean>
  max_per_member: number | null
  minutes_per_package: number
  per_min_rate: Numeric
  product_id: string
  simplbooks_item_id: string | null
  sold_count: Generated<number>
  total_packages_available: number
  total_price: Generated<Numeric | null>
  updated_at: Generated<Timestamp>
  updated_by: string
}

export interface PrepaidUsageLog {
  applied_at: Generated<Timestamp>
  flight_id: string | null
  member_package_id: number
  minutes_used: number
  note: string | null
  usage_id: Generated<number>
}

export interface ScheduleBookings {
  booking_id: string
  booking_status: BookingStatus
  booking_type: BookingType
  calendar_sequence: Generated<number>
  cancellation_note: string | null
  cancellation_reason: CancellationReason | null
  cancelled_at: Timestamp | null
  cancelled_by: string | null
  created_at: Generated<Timestamp>
  created_by: string
  description: string | null
  end_time_epoch: Int8
  end_time_utc: Generated<Timestamp>
  instructor_member_id: string | null
  member_id: string
  registration: string
  reminder_sent_at: Timestamp | null
  start_time_epoch: Int8
  start_time_utc: Generated<Timestamp>
  updated_at: Generated<Timestamp>
  updated_by: string
}

export interface Secrets {
  created_at: Generated<Timestamp>
  created_by: string
  id: Generated<Int8>
  /**
   * Class of the secret: MEMBER (visible to all flying members) or BOARD (visible only to board members with admin access)
   */
  secret_class: Generated<SecretClassType>
  /**
   * The name/description of the secret (e.g., "Club house key code")
   */
  secret_key: string
  /**
   * The actual secret value (e.g., door code, combination)
   */
  secret_value: string
  updated_at: Generated<Timestamp>
  updated_by: string
}

export interface ShopCartItems {
  cart_id: string
  cart_item_id: Generated<number>
  created_at: Generated<Timestamp>
  product_id: string
  quantity: Generated<number>
  selected_options: Json | null
  updated_at: Generated<Timestamp>
}

export interface ShopCarts {
  cart_id: string
  created_at: Generated<Timestamp>
  discount_code_id: number | null
  member_id: string
  updated_at: Generated<Timestamp>
}

export interface ShopCategories {
  category_id: string
  created_at: Generated<Timestamp>
  created_by: string
  description: Json | null
  is_active: Generated<boolean>
  name: Json
  sort_order: Generated<number>
  updated_at: Generated<Timestamp>
  updated_by: string
}

export interface ShopDiscountCodeCategories {
  category_id: string
  code_id: number
  created_at: Generated<Timestamp>
}

export interface ShopDiscountCodes {
  code: string
  code_id: Generated<number>
  created_at: Generated<Timestamp>
  created_by: string
  description: string | null
  discount_type: string
  discount_value: Numeric
  is_active: Generated<boolean>
  max_uses: number | null
  min_order_amount: Numeric | null
  updated_at: Generated<Timestamp>
  updated_by: string
  uses_count: Generated<number>
  valid_from: Generated<Timestamp>
  valid_until: Timestamp | null
}

export interface ShopOrderItems {
  order_id: string
  order_item_id: Generated<number>
  product_id: string
  product_snapshot: Json
  quantity: number
  selected_options: Json | null
  total_price: Numeric
  unit_price: Numeric
}

export interface ShopOrders {
  created_at: Generated<Timestamp>
  created_by: string
  discount_amount: Numeric | null
  discount_code_id: number | null
  invoice_id: Int8 | null
  member_id: string
  notes: string | null
  order_id: string
  status: Generated<ShopOrderStatus>
  total_amount: Numeric
  updated_at: Generated<Timestamp>
  updated_by: string
}

export interface ShopProductProperties {
  is_required: Generated<boolean>
  name: Json
  product_id: string
  property_id: Generated<number>
  sort_order: Generated<number>
}

export interface ShopProductPropertyOptions {
  is_active: Generated<boolean>
  option_id: Generated<number>
  property_id: number
  sort_order: Generated<number>
  stock_quantity: number | null
  value: Json
}

export interface ShopProducts {
  category_id: string
  created_at: Generated<Timestamp>
  created_by: string
  description: Json | null
  image_url: string | null
  is_active: Generated<boolean>
  is_published: Generated<boolean>
  low_stock_threshold: number | null
  max_order_quantity: number | null
  metadata: Json | null
  name: Json
  price: Numeric
  product_id: string
  product_type: Generated<ShopProductType>
  simplbooks_item_id: string | null
  stock_quantity: Generated<number>
  tags: Generated<string[]>
  updated_at: Generated<Timestamp>
  updated_by: string
  vat_percent: Generated<Numeric>
}

export interface StaticAirfields {
  closed: boolean | null
  ident: string
  iso_country: string | null
  name: string | null
}

export interface StatsAirfieldEfficiencyByAcYr {
  aircraft_registration: string | null
  away_mins: Numeric | null
  efficiency_pct: Numeric | null
  efnu_efnu_mins: Numeric | null
  inbound_outbound_mins: Numeric | null
  total_flight_mins: Numeric | null
  total_reserved_mins: Numeric | null
  yr: Numeric | null
}

export interface StatsAirfieldEfficiencyByAcYrMth {
  aircraft_registration: string | null
  away_mins: Numeric | null
  efficiency_pct: Numeric | null
  efnu_efnu_mins: Numeric | null
  inbound_outbound_mins: Numeric | null
  mth: Numeric | null
  total_flight_mins: Numeric | null
  total_reserved_mins: Numeric | null
  yr: Numeric | null
}

export interface StatsAirfieldEfficiencyByYr {
  away_mins: Numeric | null
  efficiency_pct: Numeric | null
  efnu_efnu_mins: Numeric | null
  inbound_outbound_mins: Numeric | null
  total_flight_mins: Numeric | null
  total_reserved_mins: Numeric | null
  yr: Numeric | null
}

export interface StatsAirfieldEfficiencyByYrMth {
  away_mins: Numeric | null
  efficiency_pct: Numeric | null
  efnu_efnu_mins: Numeric | null
  inbound_outbound_mins: Numeric | null
  mth: Numeric | null
  total_flight_mins: Numeric | null
  total_reserved_mins: Numeric | null
  yr: Numeric | null
}

export interface StatsDtoTotalFlightTimeByAc {
  aircraft_registration: string
  date: string
  flight_type: string
  total_flight_mins: number
  total_ifr_mins: number
  total_nf_mins: number
}

export interface StatsDtoTotalFlightTimeByAcYr {
  aircraft_registration: string
  flight_type: string
  total_flight_mins: number
  total_ifr_mins: number
  total_nf_mins: number
  yr: number
}

export interface StatsDtoTotalFlightTimeByAcYrMth {
  aircraft_registration: string
  flight_type: string
  mth: number
  total_flight_mins: number
  total_ifr_mins: number
  total_nf_mins: number
  yr: number
}

export interface StatsLongestShortestAvgFlightByAcYr {
  aircraft_registration: string
  average_flight: number
  longest_flight: number
  median_flight: number
  shortest_flight: number
  yr: number
}

export interface StatsMemberCountByType {
  member_count: number
  member_type: string
}

export interface StatsNonBillableTotalFlightTimeByAc {
  aircraft_registration: string
  date: string
  flight_type: string
  total_flight_mins: number
  total_ifr_mins: number
  total_nf_mins: number
}

export interface StatsNonBillableTotalFlightTimeByAcYr {
  aircraft_registration: string
  flight_type: string
  total_flight_mins: number
  total_ifr_mins: number
  total_nf_mins: number
  yr: number
}

export interface StatsNonBillableTotalFlightTimeByAcYrMth {
  aircraft_registration: string
  flight_type: string
  mth: number
  total_flight_mins: number
  total_ifr_mins: number
  total_nf_mins: number
  yr: number
}

export interface StatsReservationEfficiencyByAcYr {
  aircraft_registration: string | null
  efficiency_pct: Numeric | null
  total_flight_mins: Numeric | null
  total_reserved_mins: Numeric | null
  yr: Numeric | null
}

export interface StatsReservationEfficiencyByAcYrMth {
  aircraft_registration: string | null
  efficiency_pct: Numeric | null
  mth: Numeric | null
  total_flight_mins: Numeric | null
  total_reserved_mins: Numeric | null
  yr: Numeric | null
}

export interface StatsReservationEfficiencyByMemberYr {
  efficiency_pct: Numeric | null
  member: string | null
  total_flight_mins: Numeric | null
  total_reserved_mins: Numeric | null
  yr: Numeric | null
}

export interface StatsReservationEfficiencyByMemberYrMth {
  efficiency_pct: Numeric | null
  member: string | null
  mth: Numeric | null
  total_flight_mins: Numeric | null
  total_reserved_mins: Numeric | null
  yr: Numeric | null
}

export interface StatsReservationEfficiencyByYr {
  efficiency_pct: Numeric | null
  total_flight_mins: Numeric | null
  total_reserved_mins: Numeric | null
  yr: Numeric | null
}

export interface StatsReservationEfficiencyByYrMth {
  efficiency_pct: Numeric | null
  mth: Numeric | null
  total_flight_mins: Numeric | null
  total_reserved_mins: Numeric | null
  yr: Numeric | null
}

export interface StatsTotalCommercialFlightTimeByAcYrMth {
  aircraft_registration: string
  mth: number
  total_commercial_flight_mins: number
  yr: number
}

export interface StatsTotalFlightTimeByAcDt {
  aircraft_registration: string
  date: string
  total_flight_mins: number
}

export interface StatsTotalFlightTimeByAcFt {
  aircraft_registration: string
  date: string
  flight_type: string
  total_flight_mins: number
  total_ifr_mins: number
  total_nf_mins: number
}

export interface StatsTotalFlightTimeByAcYr {
  aircraft_registration: string | null
  total_flight_mins: Int8 | null
  yr: Numeric | null
}

export interface StatsTotalFlightTimeByAcYrFt {
  aircraft_registration: string
  flight_type: string
  total_flight_mins: number
  total_ifr_mins: number
  total_nf_mins: number
  yr: number
}

export interface StatsTotalFlightTimeByAcYrMthFt {
  aircraft_registration: string
  flight_type: string
  mth: number
  total_flight_mins: number
  total_ifr_mins: number
  total_nf_mins: number
  yr: number
}

export interface StatsTotalFlightTimeByPilot {
  date: string
  pilot: string
  total_flight_mins: number
  total_ifr_mins: number
  total_nf_mins: number
}

export interface StatsTotalFlightTimeByPilotYr {
  pilot: string
  total_flight_mins: number
  total_ifr_mins: number
  total_nf_mins: number
  yr: number
}

export interface StatsTotalFlightTimeByPilotYrMth {
  mth: number
  pilot: string
  total_flight_mins: number
  total_ifr_mins: number
  total_nf_mins: number
  yr: number
}

export interface StatsTotalFuelUpliftByAcYrMth {
  aircraft_registration: string
  mth: number
  total_fuel_uplift: number
  yr: number
}

export interface StatsTotalLandingsByAcYr {
  aircraft_registration: string
  total_landings: number
  yr: number
}

export interface StatsTotalOilUpliftByAcYrMth {
  aircraft_registration: string
  mth: number
  total_oil_uplift: number
  yr: number
}

export interface StatsVisitedAirfieldsByAc {
  aircraft_registration: string
  airfield: string
  total_visits: number
  yr: number
}

export interface DB {
  'accts.aircraft_pricing': AcctsAircraftPricing
  'accts.cost_centre': AcctsCostCentre
  'accts.expense_category': AcctsExpenseCategory
  'accts.expense_claim': AcctsExpenseClaim
  'accts.expense_claim_line_item': AcctsExpenseClaimLineItem
  'accts.expense_claim_message': AcctsExpenseClaimMessage
  'accts.expense_mileage_detail': AcctsExpenseMileageDetail
  'accts.invoice': AcctsInvoice
  'accts.items': AcctsItems
  'accts.mileage_allowance': AcctsMileageAllowance
  'accts.outbox_simplbooks': AcctsOutboxSimplbooks
  'accts.recurring_fees_processing': AcctsRecurringFeesProcessing
  'dto.flight_item_outcomes': DtoFlightItemOutcomes
  'dto.hil_queue': DtoHilQueue
  'dto.member_syllabus': DtoMemberSyllabus
  'dto.syllabus': DtoSyllabus
  'dto.syllabus_flight_attempts': DtoSyllabusFlightAttempts
  'dto.syllabus_flight_items': DtoSyllabusFlightItems
  'dto.syllabus_flights': DtoSyllabusFlights
  'dto.training_program': DtoTrainingProgram
  emt_messages: EmtMessages
  emt_processors: EmtProcessors
  emt_projections: EmtProjections
  emt_streams: EmtStreams
  'exam.attempt_answers': ExamAttemptAnswers
  'exam.attempt_questions': ExamAttemptQuestions
  'exam.attempts': ExamAttempts
  'exam.choice_translations': ExamChoiceTranslations
  'exam.choices': ExamChoices
  'exam.exam_version_translations': ExamExamVersionTranslations
  'exam.exam_versions': ExamExamVersions
  'exam.exams': ExamExams
  'exam.question_translations': ExamQuestionTranslations
  'exam.questions': ExamQuestions
  'flight.aircraft': FlightAircraft
  'flight.aircraft_cards': FlightAircraftCards
  'flight.aircraft_document_expiry_notifications': FlightAircraftDocumentExpiryNotifications
  'flight.aircraft_documents_files': FlightAircraftDocumentsFiles
  'flight.aircraft_hil': FlightAircraftHil
  'flight.aircraft_hil_audit': FlightAircraftHilAudit
  'flight.aircraft_hil_extension': FlightAircraftHilExtension
  'flight.aircraft_hil_extension_audit': FlightAircraftHilExtensionAudit
  'flight.aircraft_journey_log_book': FlightAircraftJourneyLogBook
  'flight.aircraft_landings_baseline': FlightAircraftLandingsBaseline
  'flight.aircraft_navdata': FlightAircraftNavdata
  'flight.defect': FlightDefect
  'flight.defect_audit': FlightDefectAudit
  'flight.flight_credits': FlightFlightCredits
  'flight.fuel_types': FlightFuelTypes
  'flight.logs': FlightLogs
  'flight.logs_audit': FlightLogsAudit
  'flight.maintenance_note': FlightMaintenanceNote
  'flight.maintenance_note_audit': FlightMaintenanceNoteAudit
  'flight.occurrence_access': FlightOccurrenceAccess
  'flight.occurrences': FlightOccurrences
  'flight.vw_aircraft_grounding_status': FlightVwAircraftGroundingStatus
  'flight.vw_flight_logs': FlightVwFlightLogs
  'flight.vw_flight_time_totals': FlightVwFlightTimeTotals
  flyway_data_history: FlywayDataHistory
  flyway_schema_history: FlywaySchemaHistory
  fuel_prices_content: FuelPricesContent
  'inventory.audit_log': InventoryAuditLog
  'inventory.categories': InventoryCategories
  'inventory.items': InventoryItems
  'inventory.locations': InventoryLocations
  'member.annual_fees': MemberAnnualFees
  'member.brevo_sync_state': MemberBrevoSyncState
  'member.document_tiny_urls': MemberDocumentTinyUrls
  'member.documents': MemberDocuments
  'member.events': MemberEvents
  'member.login_attempts': MemberLoginAttempts
  'member.login_events': MemberLoginEvents
  'member.member_to_roles': MemberMemberToRoles
  'member.non_renewal_actions': MemberNonRenewalActions
  'member.passkeys': MemberPasskeys
  'member.pending_email_changes': MemberPendingEmailChanges
  'member.qualification_proof_files': MemberQualificationProofFiles
  'member.register': MemberRegister
  'member.register_audit': MemberRegisterAudit
  'member.roles': MemberRoles
  'member.simplbooks_sync_state': MemberSimplbooksSyncState
  'member.webauthn_challenges': MemberWebauthnChallenges
  notification_banner: NotificationBanner
  'prepaid.member_packages': PrepaidMemberPackages
  'prepaid.packages': PrepaidPackages
  'prepaid.usage_log': PrepaidUsageLog
  'schedule.bookings': ScheduleBookings
  secrets: Secrets
  'shop.cart_items': ShopCartItems
  'shop.carts': ShopCarts
  'shop.categories': ShopCategories
  'shop.discount_code_categories': ShopDiscountCodeCategories
  'shop.discount_codes': ShopDiscountCodes
  'shop.order_items': ShopOrderItems
  'shop.orders': ShopOrders
  'shop.product_properties': ShopProductProperties
  'shop.product_property_options': ShopProductPropertyOptions
  'shop.products': ShopProducts
  'static.airfields': StaticAirfields
  'stats.airfield_efficiency_by_ac_yr': StatsAirfieldEfficiencyByAcYr
  'stats.airfield_efficiency_by_ac_yr_mth': StatsAirfieldEfficiencyByAcYrMth
  'stats.airfield_efficiency_by_yr': StatsAirfieldEfficiencyByYr
  'stats.airfield_efficiency_by_yr_mth': StatsAirfieldEfficiencyByYrMth
  'stats.dto_total_flight_time_by_ac': StatsDtoTotalFlightTimeByAc
  'stats.dto_total_flight_time_by_ac_yr': StatsDtoTotalFlightTimeByAcYr
  'stats.dto_total_flight_time_by_ac_yr_mth': StatsDtoTotalFlightTimeByAcYrMth
  'stats.longest_shortest_avg_flight_by_ac_yr': StatsLongestShortestAvgFlightByAcYr
  'stats.member_count_by_type': StatsMemberCountByType
  'stats.non_billable_total_flight_time_by_ac': StatsNonBillableTotalFlightTimeByAc
  'stats.non_billable_total_flight_time_by_ac_yr': StatsNonBillableTotalFlightTimeByAcYr
  'stats.non_billable_total_flight_time_by_ac_yr_mth': StatsNonBillableTotalFlightTimeByAcYrMth
  'stats.reservation_efficiency_by_ac_yr': StatsReservationEfficiencyByAcYr
  'stats.reservation_efficiency_by_ac_yr_mth': StatsReservationEfficiencyByAcYrMth
  'stats.reservation_efficiency_by_member_yr': StatsReservationEfficiencyByMemberYr
  'stats.reservation_efficiency_by_member_yr_mth': StatsReservationEfficiencyByMemberYrMth
  'stats.reservation_efficiency_by_yr': StatsReservationEfficiencyByYr
  'stats.reservation_efficiency_by_yr_mth': StatsReservationEfficiencyByYrMth
  'stats.total_commercial_flight_time_by_ac_yr_mth': StatsTotalCommercialFlightTimeByAcYrMth
  'stats.total_flight_time_by_ac_dt': StatsTotalFlightTimeByAcDt
  'stats.total_flight_time_by_ac_ft': StatsTotalFlightTimeByAcFt
  'stats.total_flight_time_by_ac_yr': StatsTotalFlightTimeByAcYr
  'stats.total_flight_time_by_ac_yr_ft': StatsTotalFlightTimeByAcYrFt
  'stats.total_flight_time_by_ac_yr_mth_ft': StatsTotalFlightTimeByAcYrMthFt
  'stats.total_flight_time_by_pilot': StatsTotalFlightTimeByPilot
  'stats.total_flight_time_by_pilot_yr': StatsTotalFlightTimeByPilotYr
  'stats.total_flight_time_by_pilot_yr_mth': StatsTotalFlightTimeByPilotYrMth
  'stats.total_fuel_uplift_by_ac_yr_mth': StatsTotalFuelUpliftByAcYrMth
  'stats.total_landings_by_ac_yr': StatsTotalLandingsByAcYr
  'stats.total_oil_uplift_by_ac_yr_mth': StatsTotalOilUpliftByAcYrMth
  'stats.visited_airfields_by_ac': StatsVisitedAirfieldsByAc
}
