/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely'

export type AuthEventType =
  | 'login_code_expired'
  | 'login_code_invalid'
  | 'login_code_max_attempts'
  | 'login_failed'
  | 'login_success'
  | 'logout'
  | 'passkey_login_failed'
  | 'passkey_login_success'
  | 'passkey_registered'
  | 'passkey_removed'
  | 'registration_verified'
  | 'token_refresh'

export type BookingStatus = 'CANCELLED' | 'CONFIRMED' | 'TENTATIVE'

export type BookingType = 'CROSSCOUNTRY' | 'MAINTENANCE' | 'PRACTICE' | 'PRIVATE' | 'TRAINING'

export type CancellationReason =
  | 'AIRCRAFT_TECHNICAL'
  | 'IM_SAFE_CHECKLIST'
  | 'OTHER'
  | 'PERSONAL_CONFLICT'
  | 'PREFER_NOT_DISCLOSE'
  | 'WEATHER_DEPARTURE'
  | 'WEATHER_DESTINATION'
  | 'WEATHER_ENROUTE'

export type CrewRole = 'FE' | 'FI' | 'OBS' | 'PIC' | 'STU'

export type DtoFlightType = 'DUAL' | 'DUAL_XC' | 'SOLO' | 'SOLO_XC'

export type DtoItemOutcome = 'COMPLETED' | 'FAILED' | 'MOVED_TO_HIL'

export type DtoSyllabusStatus = 'ARCHIVED' | 'DRAFT' | 'PUBLISHED' | 'WAITING_FOR_APPROVAL'

export type DtoVerificationResult = 'APPROVED' | 'FAILED'

export type ExamAttemptStatus = 'ABANDONED' | 'GRADED' | 'IN_PROGRESS' | 'SUBMITTED'

export type ExamExamType = 'AFM' | 'DTO' | 'OTHER' | 'SELF_STUDY'

export type ExamExamVersionStatus = 'DRAFT' | 'PUBLISHED' | 'RETIRED'

export type Feeprocessstatus = 'inProgress' | 'processed'

export type FeeType = 'annual_fee' | 'equipment_fee'

export type FlightAircraftDocumentType =
  | 'ARC'
  | 'Certificate of Airworthiness'
  | 'Checklist'
  | 'Finavia Season card'
  | 'Insurance Certificate'
  | 'Maintenance Manual'
  | 'Noise Certificate'
  | 'Other'
  | 'POH / AFM'
  | 'Radio Licence'
  | 'Registration'
  | 'Transponder Mode S certificate'
  | 'Weight Report'

export type FlightDefectStatus = 'ACTIVE' | 'MOVED_TO_HIL' | 'RESOLVED'

export type FlightLogStatus = 'INVOICED' | 'NEW' | 'PAID' | 'QUEUED_FOR_INVOICING' | 'VALIDATED'

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>

export type InventoryItemCondition = 'FAIR' | 'GOOD' | 'POOR' | 'UNKNOWN'

export type InventoryItemType = 'ASSET' | 'CONSUMABLE'

export type InvoiceType =
  | 'ANNUAL_FEE'
  | 'CREDIT_NOTE'
  | 'EQUIPMENT_FEE'
  | 'FLIGHT'
  | 'INSTRUCTION'
  | 'JOINING_FEE'
  | 'MISC'
  | 'SHOP_ORDER'

export type Json = JsonValue

export type JsonArray = JsonValue[]

export type JsonObject = {
  [x: string]: JsonValue | undefined
}

export type JsonPrimitive = boolean | number | string | null

export type JsonValue = JsonArray | JsonObject | JsonPrimitive

export type MemberType =
  'EXTERNAL' | 'FLYING' | 'HONORARY' | 'JUNIOR' | 'NON-FLYING' | 'REMOVED' | 'SYSTEM'

export type MikLang = 'en' | 'fi' | 'sv'

export type NonRenewalActionType = 'MEMBERSHIP_CANCELLED' | 'REMINDER_SENT'

export type Numeric = ColumnType<number, number | string, number | string>

export type Occurrencestatus =
  'ANONYMIZED' | 'ANONYMIZING' | 'CLOSED' | 'DELETED' | 'NEW' | 'PROCESSED' | 'RECEIVED'

export type SecretClassType = 'BOARD' | 'MEMBER'

export type ShopOrderStatus =
  'CANCELLED' | 'INVOICE_PAID' | 'INVOICED' | 'PENDING' | 'PROCESSING' | 'REFUNDED'

export type ShopProductType = 'FLIGHT_HOURS_PACKAGE' | 'STANDARD'

export type SimplbooksOutboxStatus = 'FAILED' | 'PENDING' | 'PROCESSING' | 'SKIPPED' | 'SYNCED'

export type Timestamp = ColumnType<Date, Date | string, Date | string>

export interface AcctsAircraftPricing {
  createdAt: Generated<Timestamp>
  createdBy: string | null
  notes: string | null
  pricePerMin: Numeric
  registration: string
  updatedAt: Generated<Timestamp | null>
  updatedBy: string | null
  validFrom: string
  validTo: string | null
}

export interface AcctsCostCentre {
  code: string
  description: string
}

export interface AcctsExpenseCategory {
  active: Generated<boolean>
  code: string
  id: Generated<number>
  labelEn: string
  labelFi: string
  labelSv: string
  requiresAircraft: Generated<boolean>
  requiresFlight: Generated<boolean>
}

export interface AcctsExpenseClaim {
  aircraftId: string | null
  approvedAt: Timestamp | null
  approvedBy: string | null
  categoryId: number
  ccy: Generated<string>
  createdAt: Generated<Timestamp>
  description: string | null
  expenseDate: string | null
  flightLogId: string | null
  fuelLitres: Numeric | null
  fuelType: string | null
  fxRate: Numeric | null
  /**
   * AES-256-GCM encrypted Finnish social security number (HETU) for mileage claims — GDPR sensitive
   */
  hetuEncrypted: string | null
  iban: string | null
  ibanAccountName: string | null
  id: Generated<string>
  memberId: string
  receiptFileName: string | null
  receiptFileSize: Int8 | null
  receiptMimeType: string | null
  receiptStorageKey: string | null
  receiptUploadedAt: Timestamp | null
  refuelOutsideFinland: Generated<boolean>
  rejectedAt: Timestamp | null
  rejectedBy: string | null
  rejectionReason: string | null
  simplbooksPurchaseId: Int8 | null
  status: Generated<string>
  submittedAt: Timestamp | null
  title: string
  updatedAt: Generated<Timestamp>
}

export interface AcctsExpenseClaimAttachment {
  claimId: string
  fileName: string
  fileSize: Int8
  id: Generated<number>
  mimeType: string
  sortOrder: Generated<number>
  storageKey: string
  uploadedAt: Generated<Timestamp>
}

export interface AcctsExpenseClaimEditAudit {
  claimId: string
  editedAt: Generated<Timestamp>
  editedBy: string
  fieldName: string
  id: Generated<number>
  /**
   * NULL for claim-level field changes (title, aircraft, expense date)
   */
  lineItemId: number | null
  newValue: string | null
  oldValue: string | null
}

export interface AcctsExpenseClaimLineItem {
  airport: string | null
  claimId: string
  costCentreCode: string | null
  description: string
  fuelDate: string | null
  fuelType: string | null
  id: Generated<number>
  itemId: number | null
  /**
   * Fuel bought with the club's card, not reimbursed to the member
   */
  paidWithClubCard: Generated<boolean>
  quantity: Generated<Numeric>
  sortOrder: Generated<number>
  totalCost: Numeric | null
  unit: Generated<string>
  unitPrice: Numeric
}

export interface AcctsExpenseClaimMessage {
  body: string
  claimId: string
  id: Generated<number>
  messageType: string
  senderId: string
  sentAt: Generated<Timestamp>
}

export interface AcctsExpenseMileageDetail {
  /**
   * True when the journey exceeded the km soft-limit and board approval has been confirmed
   */
  boardApproved: Generated<boolean>
  claimId: string
  createdAt: Generated<Timestamp>
  /**
   * Server-computed start->end distance with no waypoints, for comparison against distance_km
   */
  directDistanceKm: Numeric | null
  distanceKm: Numeric
  /**
   * Structured end address label (from geocoding search)
   */
  endAddress: string | null
  endLat: Numeric | null
  endLon: Numeric | null
  id: Generated<number>
  /**
   * Date of the journey
   */
  journeyDate: string
  /**
   * Required when distance_km exceeds direct_distance_km by more than 20%
   */
  justificationNote: string | null
  /**
   * Effective rate at time of claim creation (rate_per_km * (1 - discount_pct/100))
   */
  ratePerKm: Numeric
  /**
   * Legacy free-text route, only populated on claims created before issue #1021
   */
  route: string | null
  /**
   * Structured start address label (from geocoding search)
   */
  startAddress: string | null
  startLat: Numeric | null
  startLon: Numeric | null
  updatedAt: Generated<Timestamp>
  /**
   * Ordered [{label, lat, lon}, ...] intermediate stops for non-direct routes
   */
  waypoints: Generated<Json>
}

export interface AcctsInvoice {
  createdAt: Generated<Timestamp>
  createdBy: string
  currency: Generated<string>
  description: string | null
  dueAt: string
  id: Int8
  invoiceType: InvoiceType
  isPaid: Generated<boolean>
  memberId: string
  overdueEmailSentAt: Timestamp | null
  paidAt: string | null
  pmtRef: string
  sentAt: string | null
  totalSum: Numeric | null
  updatedAt: Generated<Timestamp>
  updatedBy: string
}

export interface AcctsItems {
  code: string
  expenseClaimItem: Generated<boolean>
  id: number
  isFuelItem: Generated<boolean>
  isKmItem: Generated<boolean>
  isOtherItem: Generated<boolean>
  item: Json | null
  name: string
}

export interface AcctsLocalFuelPrice {
  createdAt: Generated<Timestamp>
  createdBy: string
  fuelType: string
  id: Generated<number>
  /**
   * Total price including fuel tax, EUR per litre
   */
  priceEurPerLitre: Numeric
  /**
   * Effective from this date until the next row for the same fuel_type
   */
  validFrom: string
}

export interface AcctsMileageAllowance {
  createdAt: Generated<Timestamp>
  createdBy: string
  /**
   * Percentage of the official rate that the club actually pays (default 50%)
   */
  discountPct: Generated<Numeric>
  id: Generated<number>
  /**
   * Official rate €/km as published by the Finnish Tax Administration
   */
  ratePerKm: Numeric
  taxYear: number
  updatedAt: Generated<Timestamp>
  updatedBy: string
}

export interface AcctsMileageHetuAccessAudit {
  accessedAt: Generated<Timestamp>
  /**
   * Member who revealed the HETU (must hold expense.hetu_admin)
   */
  accessedBy: string
  claimId: string
  /**
   * Where the reveal happened, e.g. CLAIM_REVEAL
   */
  context: string
  id: Generated<number>
}

export interface AcctsOutboxSimplbooks {
  createdAtUtc: Generated<Timestamp>
  errorMessage: string | null
  eventType: string
  id: string
  payload: Json
  processedAt: Timestamp | null
  status: Generated<SimplbooksOutboxStatus>
  updatedAtUtc: Generated<Timestamp>
}

export interface AcctsRecurringFeesProcessing {
  createdAt: Generated<Timestamp>
  createdBy: string
  feeType: FeeType
  status: Feeprocessstatus
  updatedAt: Generated<Timestamp>
  updatedBy: string
  year: number
}

export interface ClubAmeEditSuggestion {
  ameId: string
  createdAt: Generated<Timestamp>
  id: Generated<string>
  location: string
  medicalCentre: string
  medicalTypes: Generated<string[]>
  name: string
  notes: string | null
  price: Numeric | null
  rejectionReason: string | null
  reportDate: string
  reviewedAt: Timestamp | null
  reviewedBy: string | null
  status: Generated<string>
  submittedBy: string
  updatedAt: Generated<Timestamp>
}

export interface ClubAmeList {
  approvedAt: Timestamp | null
  approvedBy: string | null
  createdAt: Generated<Timestamp>
  id: Generated<string>
  location: string
  medicalCentre: string
  medicalTypes: Generated<string[]>
  name: string
  notes: string | null
  price: Numeric | null
  rejectedAt: Timestamp | null
  rejectedBy: string | null
  rejectionReason: string | null
  reportDate: string
  status: Generated<string>
  submittedBy: string
  updatedAt: Generated<Timestamp>
}

export interface ClubAmeRating {
  ameId: string
  createdAt: Generated<Timestamp>
  id: Generated<string>
  memberId: string
  stars: number
  updatedAt: Generated<Timestamp>
}

export interface ClubAmeRemovalRequest {
  ameId: string
  createdAt: Generated<Timestamp>
  id: Generated<string>
  reason: string
  rejectionReason: string | null
  reviewedAt: Timestamp | null
  reviewedBy: string | null
  status: Generated<string>
  submittedBy: string
  updatedAt: Generated<Timestamp>
}

export interface DtoFlightItemOutcomes {
  attemptId: string
  createdAt: Generated<Timestamp>
  itemId: string
  outcome: DtoItemOutcome
  remarks: string | null
  updatedAt: Generated<Timestamp>
}

export interface DtoHilQueue {
  hilId: Generated<string>
  itemId: string
  memberId: string
  notes: string | null
  openedAt: Generated<Timestamp>
  openedOnAttemptId: string
  resolutionOutcome: DtoItemOutcome | null
  resolvedAt: Timestamp | null
  resolvedOnAttemptId: string | null
  syllabusId: string
}

export interface DtoMemberSyllabus {
  assignedAt: Generated<Timestamp>
  assignedBy: string
  deactivatedAt: Timestamp | null
  isActive: Generated<boolean>
  memberId: string
  memberSyllabusId: Generated<string>
  syllabusId: string
}

export interface DtoSyllabus {
  approvalReference: string | null
  createdAt: Generated<Timestamp>
  createdBy: string
  description: string | null
  generalInformation: string | null
  majorVersion: number
  minBlockTimeMins: number | null
  minorVersion: number
  patchVersion: Generated<number>
  programId: string
  publishedAt: Timestamp | null
  requirementsExperienceCredit: string | null
  status: Generated<DtoSyllabusStatus>
  submittedForApprovalAt: Timestamp | null
  syllabusId: Generated<string>
  updatedAt: Generated<Timestamp>
  updatedBy: string
  version: Generated<string | null>
}

export interface DtoSyllabusFlightAttempts {
  attemptId: Generated<string>
  createdAt: Generated<Timestamp>
  flightLogId: string
  instructorComments: string | null
  instructorMemberId: string
  memberSyllabusId: string
  requiresReverification: Generated<boolean>
  syllabusFlightId: string
  updatedAt: Generated<Timestamp>
  verificationResult: DtoVerificationResult | null
  verifiedAt: Timestamp | null
  verifiedBy: string | null
}

export interface DtoSyllabusFlightItems {
  description: string | null
  itemId: Generated<string>
  mandatory: Generated<boolean>
  name: string
  sortOrder: number
  syllabusFlightId: string
}

export interface DtoSyllabusFlights {
  code: string
  createdAt: Generated<Timestamp>
  description: string | null
  easaFclReference: string | null
  flightId: Generated<string>
  flightType: DtoFlightType | null
  isInterimCheckpoint: Generated<boolean>
  name: string
  recommendedBlockTimeMins: number | null
  sortOrder: number
  syllabusId: string
  tags: Generated<string[]>
  updatedAt: Generated<Timestamp>
}

export interface DtoTrainingProgram {
  createdAt: Generated<Timestamp>
  createdBy: string
  description: string | null
  name: string
  programId: Generated<string>
  updatedAt: Generated<Timestamp>
  updatedBy: string
}

export interface EmtMessages {
  created: Generated<Timestamp>
  globalPosition: Generated<Int8 | null>
  isArchived: Generated<boolean>
  messageData: Json
  messageId: string
  messageKind: Generated<string>
  messageMetadata: Json
  messageSchemaVersion: string
  messageType: string
  partition: Generated<string>
  streamId: string
  streamPosition: Int8
  transactionId: string
}

export interface EmtProcessors {
  createdAt: Generated<Timestamp>
  lastProcessedCheckpoint: string
  lastProcessedTransactionId: string
  lastUpdated: Generated<Timestamp>
  partition: Generated<string>
  processorId: string
  processorInstanceId: Generated<string | null>
  status: Generated<string>
  version: Generated<number>
}

export interface EmtProjections {
  createdAt: Generated<Timestamp>
  definition: Generated<Json>
  kind: string
  lastUpdated: Generated<Timestamp>
  name: string
  partition: Generated<string>
  status: string
  type: string
  version: Generated<number>
}

export interface EmtStreams {
  isArchived: Generated<boolean>
  partition: Generated<string>
  streamId: string
  streamMetadata: Json
  streamPosition: Int8
  streamType: string
}

export interface ExamAttemptAnswers {
  attemptId: string
  choiceId: string | null
  createdAt: Generated<Timestamp>
  questionId: string
  updatedAt: Generated<Timestamp>
}

export interface ExamAttemptQuestions {
  attemptId: string
  questionId: string
  sortOrder: Generated<number>
}

export interface ExamAttempts {
  abandonedAt: Timestamp | null
  abandonReason: string | null
  attemptId: string
  correctCount: number | null
  createdAt: Generated<Timestamp>
  gradedAt: Timestamp | null
  language: Generated<string>
  memberId: string
  passed: boolean | null
  scorePercent: Numeric | null
  status: Generated<ExamAttemptStatus>
  submittedAt: Timestamp | null
  totalCount: number | null
  updatedAt: Generated<Timestamp>
  versionId: string
}

export interface ExamChoices {
  choiceId: string
  isCorrect: Generated<boolean>
  questionId: string
  sortOrder: Generated<number>
}

export interface ExamChoiceTranslations {
  choiceId: string
  language: string
  text: string
}

export interface ExamExams {
  createdAt: Generated<Timestamp>
  createdBy: string
  examId: string
  examType: Generated<ExamExamType>
  name: string
  updatedAt: Generated<Timestamp>
  updatedBy: string
}

export interface ExamExamVersions {
  createdAt: Generated<Timestamp>
  createdBy: string
  defaultLanguage: Generated<string>
  examId: string
  passPercent: Generated<Numeric>
  /**
   * When set, each attempt draws this many randomly-selected questions from the version pool. NULL means all questions are used.
   */
  questionCount: number | null
  /**
   * When true (the default, and the behaviour of every version created before this column existed), each attempt shuffles the questions and question_count may draw a random subset. When false the attempt presents every question of the version in the authored sort_order and question_count is ignored.
   */
  randomizeQuestionOrder: Generated<boolean>
  status: Generated<ExamExamVersionStatus>
  supportedLanguages: Generated<string[]>
  updatedAt: Generated<Timestamp>
  updatedBy: string
  versionId: string
  versionNumber: Generated<number>
}

export interface ExamExamVersionTranslations {
  description: string | null
  language: string
  title: string
  versionId: string
}

export interface ExamQuestions {
  questionId: string
  sortOrder: Generated<number>
  versionId: string
}

export interface ExamQuestionTranslations {
  language: string
  prompt: string
  questionId: string
  reasoning: string | null
}

export interface FlightAircraft {
  active: Generated<boolean>
  createdAt: Generated<Timestamp>
  createdBy: string
  displayName: string
  equipment: string | null
  fuelTypes: string[]
  hidden: Generated<boolean>
  imageUrl: string | null
  lastMaintenanceDate: string
  lastMaintenanceMins: number
  lastMaintenanceType: string
  location: string | null
  maintenanceCycle: number
  manufacturer: string
  model: string
  nextMaintenanceDate: string | null
  nextMaintenanceMins: number
  nextMaintenanceType: string
  notes: Json | null
  preferredFuelType: string | null
  registration: string
  reservedHours: number
  seats: number
  totalPercentageHours: number
  updatedAt: Generated<Timestamp>
  updatedBy: string
  usableFuelLitres: number
  yearOfManufacture: number
}

export interface FlightAircraftCards {
  aircraftRegistration: string
  cardId: Generated<number>
  createdAt: Generated<Timestamp>
  createdBy: string
  description: string | null
  name: string
  updatedAt: Generated<Timestamp>
  updatedBy: string
  validFrom: string | null
  validTo: string | null
}

export interface FlightAircraftDocumentExpiryNotifications {
  daysThreshold: Generated<number>
  documentId: number
  id: Generated<number>
  notificationType: string
  sentAt: Generated<Timestamp>
}

export interface FlightAircraftDocumentsFiles {
  aircraftRegistration: string
  createdAt: Generated<Timestamp>
  createdBy: string
  description: string | null
  documentId: Generated<number>
  documentType: FlightAircraftDocumentType
  documentUrl: string
  fileName: string
  fileSize: number | null
  isActive: Generated<boolean>
  mimeType: string | null
  storageKey: string | null
  title: string
  updatedAt: Generated<Timestamp>
  updatedBy: string
  validFrom: string | null
  validTo: string | null
}

export interface FlightAircraftHil {
  aircraftRegistration: string
  createdAt: Generated<Timestamp>
  createdBy: string
  defectCat: string | null
  description: string
  dueDate: Timestamp | null
  hilId: Generated<string>
  hilNumber: number
  name: string
  openDate: Timestamp
  resolvedNoteId: string | null
  restrictions: string | null
  sourceRef: string | null
  updatedAt: Generated<Timestamp>
  updatedBy: string
}

export interface FlightAircraftHilAudit {
  auditId: Generated<number>
  changedAt: Generated<Timestamp>
  changedBy: string
  changedData: Json | null
  hilId: string
  newData: Json | null
  operationType: string
}

export interface FlightAircraftHilExtension {
  createdAt: Generated<Timestamp>
  createdBy: string
  extensionDate: Timestamp
  extensionDue: Timestamp
  extensionId: Generated<string>
  hilId: string
  name: string
}

export interface FlightAircraftHilExtensionAudit {
  auditId: Generated<number>
  changedAt: Generated<Timestamp>
  changedBy: string
  changedData: Json | null
  extensionId: string
  newData: Json | null
  operationType: string
}

export interface FlightAircraftJourneyLogBook {
  aircraftRegistration: string
  createdAt: Generated<Timestamp>
  createdBy: string
  endDate: string | null
  noOfPages: number
  rowsPerPage: number
  seqNo: number
  startDate: string
  startFlightMins: number
  startFlightTime: Generated<string>
  startLandings: Generated<number>
  startPage: number
  updatedAt: Generated<Timestamp>
  updatedBy: string
}

export interface FlightAircraftLandingsBaseline {
  aircraftRegistration: string
  baselineLandings: number
  createdAt: Generated<Timestamp>
  createdBy: string | null
  updatedAt: Generated<Timestamp>
  updatedBy: string | null
}

export interface FlightAircraftNavdata {
  aircraftRegistration: string
  createdAt: Generated<Timestamp>
  createdBy: string
  cycle: string
  expires: string
  navdataId: Generated<string>
  updateDate: string
  updaterMemberId: string
}

export interface FlightDefect {
  aircraftRegistration: string
  ajlbSeqNo: number
  createdAt: Generated<Timestamp>
  createdBy: string
  defectId: Generated<string>
  description: string
  flightId: string | null
  flightMins: number
  hilId: string | null
  resolvedNoteId: string | null
  rows: Generated<number>
  status: Generated<FlightDefectStatus>
  updatedAt: Generated<Timestamp>
  updatedBy: string
}

export interface FlightDefectAudit {
  auditId: Generated<number>
  changedAt: Generated<Timestamp>
  changedBy: string
  changedData: Json | null
  defectId: string
  newData: Json | null
  operationType: string
}

export interface FlightFlightCredits {
  allocatedByMemberId: string
  createdAt: Generated<Timestamp>
  creditedMins: number
  flightId: string
  note: string | null
  updatedAt: Generated<Timestamp>
}

export interface FlightFuelTypes {
  name: string
  sortOrder: Generated<number>
}

export interface FlightLogs {
  aircraftRegistration: string
  ajlbBlankRowsBefore: number
  ajlbPageNumber: number | null
  ajlbRowNumber: number | null
  ajlbSeqNo: number
  ajlbTotalFlightMins: number | null
  ajlbTotalFlightTime: Generated<string | null>
  ajlbTotalLandings: number | null
  arrivalAirport: string
  billableMemberId: string
  billingRemarks: string | null
  blockMins: Generated<number>
  blockTime: Generated<string>
  createdAt: Generated<Timestamp>
  createdBy: string
  crew2LastName: string | null
  crew2MemberId: Generated<string | null>
  crew2Role: CrewRole | null
  crew3LastName: string | null
  crew3MemberId: Generated<string | null>
  crew3Role: CrewRole | null
  crew4LastName: string | null
  crew4MemberId: Generated<string | null>
  crew4Role: CrewRole | null
  departureAirport: string
  entryErrorFee: Generated<boolean>
  entryErrorFeeAppliedByMemberId: string | null
  flightId: string
  flightMins: Generated<number>
  flightTime: Generated<string>
  flightType: string
  fuelRemainingLitres: Numeric
  fuelUpliftLitres: Numeric | null
  incidentOrObservations: string | null
  instrumentFlyingMins: number
  invoiceNumber: Generated<string | null>
  isBillableFlight: boolean
  isBilled: Generated<boolean>
  isDtoTrainingFlight: boolean
  landingTimeEpoch: Int8
  landingTimeUtc: Generated<Timestamp>
  minBillableExceptionApprovedByMemberId: string | null
  minBillableExceptionReason: string | null
  nightFlyingMins: number
  nonBillingApprovedByMemberId: string | null
  nonBillingReason: string | null
  numberOfLandings: number
  numberOfNightLandings: Generated<number>
  offBlockTimeEpoch: Int8
  offBlockTimeUtc: Generated<Timestamp>
  oilUpliftLitres: Numeric | null
  onBlockTimeEpoch: Int8
  onBlockTimeUtc: Generated<Timestamp>
  partiallyBillableFlight: Generated<boolean>
  personalRemarks: string | null
  personsOnBoard: number
  picLastName: string
  picMemberId: string
  picRole: CrewRole
  privOrComFlight: string
  status: Generated<FlightLogStatus>
  takeoffTimeEpoch: Int8
  takeoffTimeUtc: Generated<Timestamp>
  totalTimeInService: Numeric | null
  updatedAt: Generated<Timestamp>
  updatedBy: string
  validationRemarks: string | null
}

export interface FlightLogsAudit {
  auditId: Generated<number>
  changedAt: Generated<Timestamp>
  changedBy: string
  changedData: Json | null
  flightId: string
  newData: Json | null
  operationType: string
}

export interface FlightMaintenanceNote {
  aircraftRegistration: string
  ajlbSeqNo: number
  createdAt: Generated<Timestamp>
  createdBy: string
  description: string
  flightMins: number
  noteId: Generated<string>
  performedBy: string
  rows: Generated<number>
  updatedAt: Generated<Timestamp>
  updatedBy: Generated<string>
}

export interface FlightMaintenanceNoteAudit {
  auditId: Generated<number>
  changedAt: Generated<Timestamp>
  changedBy: string
  changedData: Json | null
  newData: Json | null
  noteId: string
  operationType: string
}

export interface FlightOccurrenceAccess {
  accessId: Generated<number>
  author: Generated<boolean>
  manageAccess: Generated<boolean>
  memberId: string | null
  reportId: string
  roleId: string | null
  updatedAt: Generated<Timestamp>
  updatedBy: string
  writeAccess: Generated<boolean>
}

export interface FlightOccurrenceAttachments {
  attachmentId: Generated<number>
  createdAt: Generated<Timestamp>
  createdBy: string
  fileName: string
  fileSize: number
  mimeType: string
  originStatus: Occurrencestatus
  removedAt: Timestamp | null
  removedBy: string | null
  reportId: string
  storageKey: string
  updatedAt: Generated<Timestamp>
  updatedBy: string
}

export interface FlightOccurrences {
  animalNumber: string | null
  animalSize: string | null
  animalSpecies: string | null
  arrivalAirport: string | null
  categories: Json
  comments: Generated<Json>
  createdAt: Generated<Timestamp>
  createdBy: string
  deadLine: Timestamp | null
  departureAirport: string | null
  description: string
  handling: Generated<Json>
  headline: string
  isDtoReport: boolean
  isWeatherRelevant: boolean | null
  linkedReportId: string | null
  location: string
  notifiedAt: Timestamp | null
  notifiedStatus: Occurrencestatus | null
  occurrenceDate: Timestamp
  processedDate: Timestamp | null
  registration: string | null
  reportDate: Timestamp
  reportId: string
  status: Generated<Occurrencestatus>
  technicalFaults: boolean | null
  updatedAt: Generated<Timestamp>
  updatedBy: string
}

export interface FlightRemark {
  createdAt: Generated<Timestamp>
  createdBy: string
  description: string
  flightId: string
  remarkId: Generated<string>
  updatedAt: Generated<Timestamp>
  updatedBy: string
}

export interface FlightRemarkAudit {
  auditId: Generated<number>
  changedAt: Generated<Timestamp>
  changedBy: string
  changedData: Json | null
  newData: Json | null
  operationType: string
  remarkId: string
}

export interface FlightVwAircraftGroundingStatus {
  openDefectCount: Int8 | null
  registration: string | null
}

export interface FlightVwAjlbLiveRows {
  aircraftRegistration: string | null
  ajlbSeqNo: number | null
  isContentRow: boolean | null
  itemId: string | null
  itemType: string | null
  pageNumber: number | null
  rowNumber: number | null
}

export interface FlightVwAjlbLiveSequence {
  acTotalFlightMins: Int8 | null
  acTotalLandings: Int8 | null
  aircraftRegistration: string | null
  ajlbRowNumber: Int8 | null
  ajlbSeqNo: number | null
  anchorFlightId: string | null
  itemId: string | null
  itemType: string | null
  rowsConsumed: number | null
  rowsPerPage: number | null
  startPage: number | null
}

export interface FlightVwFlightLogs {
  acTotalFlightMins: number | null
  acTotalFlightTime: string | null
  acTotalLandings: number | null
  flightId: string | null
  pageNumber: number | null
  rowNumber: number | null
}

export interface FlightVwFlightTimeTotals {
  aircraftRegistration: string | null
  ajlbSeqNo: number | null
  current: boolean | null
  lastPage: number | null
  newFlightsPage: number | null
  sumNewFlights: number | null
  sumNewTime: string | null
  sumValidatedFlights: number | null
  sumValidatedTime: string | null
  totalLandings: number | null
  unverifiedTotalFlightMins: number | null
  unverifiedTotalFlightTime: string | null
  validatedOnBlockTimeUtc: Timestamp | null
  validatedTotalFlightMins: number | null
  validatedTotalLandings: number | null
  verifiedTotalFlightTime: string | null
}

export interface FlywayDataHistory {
  checksum: number | null
  description: string
  executionTime: number
  installedBy: string
  installedOn: Generated<Timestamp>
  installedRank: number
  script: string
  success: boolean
  type: string
  version: string | null
}

export interface FlywaySchemaHistory {
  checksum: number | null
  description: string
  executionTime: number
  installedBy: string
  installedOn: Generated<Timestamp>
  installedRank: number
  script: string
  success: boolean
  type: string
  version: string | null
}

export interface FuelPricesContent {
  createdAt: Generated<Timestamp>
  createdBy: string
  id: number
  markdown: Generated<string>
  updatedAt: Generated<Timestamp>
  updatedBy: string
}

export interface InventoryAuditLog {
  changeType: string
  createdAt: Generated<Timestamp>
  itemId: string
  logId: Generated<number>
  memberId: string
  newValue: Json | null
  notes: string | null
  oldValue: Json | null
}

export interface InventoryCategories {
  categoryId: string
  createdAt: Generated<Timestamp>
  createdBy: string
  description: Json | null
  isActive: Generated<boolean>
  name: Json
  sortOrder: Generated<number>
  updatedAt: Generated<Timestamp>
  updatedBy: string
}

export interface InventoryItems {
  categoryId: string
  condition: Generated<InventoryItemCondition>
  createdAt: Generated<Timestamp>
  createdBy: string
  description: Json | null
  imageUrl: string | null
  isActive: Generated<boolean>
  itemId: string
  itemType: Generated<InventoryItemType>
  locationId: string | null
  lowStockThreshold: number | null
  name: Json
  notes: string | null
  quantity: Generated<number>
  serialNumber: string | null
  tags: Generated<string[]>
  updatedAt: Generated<Timestamp>
  updatedBy: string
}

export interface InventoryLocations {
  createdAt: Generated<Timestamp>
  createdBy: string
  description: Json | null
  isActive: Generated<boolean>
  locationId: string
  name: Json
  sortOrder: Generated<number>
  updatedAt: Generated<Timestamp>
  updatedBy: string
}

export interface MemberAnnualFees {
  createdAt: Generated<Timestamp>
  createdBy: string
  feeType: FeeType
  invoiceId: number
  memberId: string
  updatedAt: Generated<Timestamp>
  updatedBy: string
  year: number
}

export interface MemberBrevoCampaignArchiveState {
  campaignsArchived: Generated<number>
  createdAt: Generated<Timestamp>
  errorMessage: string | null
  id: Generated<number>
  lastSyncedAt: Timestamp
  syncStatus: string
}

export interface MemberBrevoSyncState {
  createdAt: Generated<Timestamp>
  errorMessage: string | null
  id: Generated<number>
  lastSyncedAt: Generated<Timestamp>
  membersSynced: Generated<number>
  syncStatus: Generated<string>
}

export interface MemberDocuments {
  category: string
  createdAt: Generated<Timestamp>
  createdBy: string
  description: string | null
  documentId: Generated<number>
  documentUrl: string | null
  /**
   * Original filename of uploaded file
   */
  fileName: string | null
  /**
   * File size in bytes
   */
  fileSize: number | null
  isArchived: Generated<boolean>
  isPublic: Generated<boolean>
  /**
   * MIME type of uploaded file
   */
  mimeType: string | null
  publishedDate: Generated<string>
  /**
   * Storage key for Digital Ocean Spaces
   */
  storageKey: string | null
  tags: string[] | null
  title: string
  updatedAt: Generated<Timestamp>
  updatedBy: string
}

export interface MemberDocumentTinyUrls {
  accessCount: Generated<number>
  aircraftDocumentId: number | null
  createdAt: Generated<Timestamp>
  createdBy: string
  documentId: number | null
  documentType: string
  expiresAt: Timestamp
  lastAccessedAt: Timestamp | null
  shortCode: string
  url: string
}

export interface MemberEvents {
  createdAt: Generated<Timestamp>
  createdBy: string
  description: string | null
  endTime: Timestamp
  eventId: Generated<string>
  imageKey: string | null
  imageUrl: string | null
  isPublic: Generated<boolean>
  location: string | null
  performer: string | null
  startTime: Timestamp
  title: string
  updatedAt: Generated<Timestamp>
  updatedBy: string
}

export interface MemberEventTranslations {
  description: string | null
  eventId: string
  language: string
  title: string
}

export interface MemberLoginAttempts {
  codeHash: string
  createdAt: Generated<Timestamp>
  email: string
  expiresAt: Timestamp
  failedAttempts: Generated<number>
  id: Generated<string>
  ipAddress: string | null
  linkTokenHash: string | null
  usedAt: Timestamp | null
}

export interface MemberLoginEvents {
  createdAt: Generated<Timestamp>
  eventType: AuthEventType
  id: Generated<string>
  ipAddress: string | null
  memberId: string | null
  userAgent: string | null
}

export interface MemberMailboxMessages {
  body: string | null
  createdAt: Generated<Timestamp>
  dedupKey: string | null
  expiresAt: Generated<Timestamp>
  id: Generated<Int8>
  readAt: Timestamp | null
  recipientId: string
  severity: Generated<string>
  title: string
  type: string
}

export interface MemberMeeting {
  createdAt: Generated<Timestamp>
  createdBy: string | null
  description: string | null
  documentSearchFilter: string | null
  endedAt: Timestamp | null
  meetingId: Generated<string>
  meetingNotesDocumentId: number | null
  meetingUrl: string | null
  startedAt: Timestamp | null
  status: Generated<string>
  title: string
}

export interface MemberMeetingAttendance {
  joinedAt: Generated<Timestamp>
  meetingId: string
  memberId: string
}

export interface MemberMeetingVote {
  closedAt: Timestamp | null
  closedBy: string | null
  createdAt: Generated<Timestamp>
  createdBy: string | null
  description: string | null
  displayOrder: Generated<number>
  isMultiSelect: Generated<boolean>
  maxSelections: number | null
  meetingId: string
  status: Generated<string>
  topic: string
  voteId: Generated<string>
}

export interface MemberMeetingVoteCounter {
  assignedAt: Generated<Timestamp>
  assignedBy: string | null
  meetingId: string
  memberId: string
}

export interface MemberMemberToRoles {
  createdAt: Generated<Timestamp>
  createdBy: string
  memberId: string
  roleId: string
}

export interface MemberNonRenewalActions {
  /**
   * REMINDER_SENT = final reminder email sent; MEMBERSHIP_CANCELLED = membership deactivated
   */
  actionType: NonRenewalActionType
  id: Generated<number>
  memberId: string
  notes: string | null
  performedAt: Generated<Timestamp>
  performedBy: string
}

export interface MemberPasskeys {
  backedUp: Generated<boolean>
  counter: Generated<Int8>
  createdAt: Generated<Timestamp>
  credentialId: string
  deviceType: string | null
  id: Generated<string>
  lastUsedAt: Timestamp | null
  memberId: string
  name: string | null
  publicKey: Buffer
  transports: Generated<string[]>
}

export interface MemberPendingEmailChanges {
  createdAt: Generated<Timestamp>
  expiresAt: Timestamp
  id: Generated<string>
  memberId: string
  newEmail: string
  tokenHash: string
  usedAt: Timestamp | null
}

export interface MemberPushSubscriptions {
  createdAt: Generated<Timestamp>
  endpoint: string
  id: Generated<string>
  keysAuth: string
  keysP256dh: string
  memberId: string
  userAgent: string | null
}

export interface MemberQualificationProofFiles {
  documentCategory: Generated<string>
  fileName: string
  historyId: Int8 | null
  id: Generated<number>
  memberId: string
  mimeType: string
  storageKey: string
  uploadedAt: Generated<Timestamp>
  uploadedBy: string
}

export interface MemberRegister {
  /**
   * Registration application data: flight hours, aircraft types, motivation, cover letter, declarations, etc.
   */
  applicationData: Json | null
  autoRenewAnnualMembership: Generated<boolean | null>
  autoRenewEquipmentFee: Generated<boolean | null>
  billingId: string | null
  brevoContactId: Int8 | null
  brevoSyncedAt: Timestamp | null
  brevoSyncStatus: Generated<string | null>
  canMakeReservations: Generated<boolean>
  country: Generated<string>
  createdAt: Generated<Timestamp>
  createdBy: string
  /**
   * User preferences for dashboard component order and visibility. Structure: {"components": [{"id": "weather", "visible": true, "order": 0}, ...]}
   */
  dashboardSettings: Json | null
  dateOfBirth: string | null
  defaultInstructorMemberId: string | null
  email: string
  emailVerifiedAt: Timestamp | null
  firstName: string
  iban: string | null
  ibanAccountName: string | null
  iceContactName: string | null
  iceContactPhoneCountry: Generated<string>
  iceContactPhoneNumber: string | null
  imDiscord: string | null
  imFacebookMessenger: string | null
  imSignal: string | null
  imTelegram: string | null
  imViber: string | null
  imWhatsapp: string | null
  isMembershipApproved: Generated<boolean>
  isMembershipExpired: Generated<boolean | null>
  isTrainingProgramPilot: Generated<boolean>
  langIso639: Generated<MikLang>
  lastName: string
  licenceExpiryDate: string | null
  licenceId: string | null
  /**
   * Aircraft mailing list subscriptions. Structure: ["list-id-1", "list-id-2"]
   */
  mailingLists: Json | null
  medicalClass1ExpiryDate: string | null
  medicalClass2ExpiryDate: string | null
  medicalExpiryDate: string | null
  medicalLaplExpiryDate: string | null
  memberId: string
  membershipApprovedAt: Timestamp | null
  membershipApprovedBy: string | null
  memberSince: Generated<string>
  memberType: MemberType
  mustUpdateProfile: Generated<boolean>
  phoneCountry: Generated<string>
  phoneNumber: string | null
  postcode: string | null
  /**
   * JSON snapshot of member state (memberType, canMakeReservations, autoRenewAnnualMembership, autoRenewEquipmentFee) taken before deactivation, used to accurately restore the member. Cleared on restore.
   */
  preRemovalSnapshot: Json | null
  removalReason: string | null
  removedAt: Timestamp | null
  removedBy: string | null
  simplbooksSyncedAt: Timestamp | null
  simplbooksSyncStatus: Generated<string | null>
  streetAddress: string | null
  townCity: string | null
  updatedAt: Generated<Timestamp>
  updatedBy: string
}

export interface MemberRegisterAudit {
  auditId: Generated<number>
  changedAt: Generated<Timestamp>
  changedBy: string
  changedData: Json | null
  memberId: string
  newData: Json | null
  operationType: string
}

export interface MemberRoles {
  createdAt: Generated<Timestamp>
  createdBy: string
  description: string | null
  isPublic: Generated<boolean>
  nameEn: string
  nameFi: string
  nameSv: string
  permissions: Json | null
  roleId: string
  updatedAt: Generated<Timestamp>
  updatedBy: string
}

export interface MemberSimplbooksSyncState {
  createdAt: Generated<Timestamp>
  errorMessage: string | null
  id: Generated<number>
  lastSyncedAt: Generated<Timestamp>
  membersSynced: Generated<number>
  syncStatus: Generated<string>
}

export interface MemberVoteCast {
  castAt: Generated<Timestamp>
  castId: Generated<string>
  memberId: string
  voteId: string
}

export interface MemberVoteOption {
  displayOrder: Generated<number>
  optionId: Generated<string>
  optionText: string
  voteId: string
}

export interface MemberVoteSelection {
  optionId: string
  selectedAt: Generated<Timestamp>
  selectionId: Generated<string>
  voteId: string
}

export interface MemberWebauthnChallenges {
  challenge: string
  createdAt: Generated<Timestamp>
  email: string | null
  expiresAt: Timestamp
  id: Generated<string>
  memberId: string | null
  purpose: string
}

export interface NotificationBanner {
  enabled: Generated<boolean>
  id: Generated<number>
  message: string | null
  severity: Generated<string>
  updatedAt: Generated<Timestamp>
  updatedBy: string | null
}

export interface PrepaidMemberPackages {
  createdAt: Generated<Timestamp>
  expiresAt: string
  isExpired: Generated<boolean>
  memberId: string
  memberPackageId: Generated<number>
  orderId: string | null
  productId: string
  remainingMinutes: Generated<number | null>
  totalMinutes: number
  updatedAt: Generated<Timestamp>
  usedMinutes: Generated<number>
}

export interface PrepaidPackages {
  aircraftRegistration: string
  createdAt: Generated<Timestamp>
  createdBy: string
  expiresAt: string
  isActive: Generated<boolean>
  maxPerMember: number | null
  minutesPerPackage: number
  perMinRate: Numeric
  productId: string
  simplbooksItemId: string | null
  soldCount: Generated<number>
  totalPackagesAvailable: number
  totalPrice: Generated<Numeric | null>
  updatedAt: Generated<Timestamp>
  updatedBy: string
}

export interface PrepaidUsageLog {
  appliedAt: Generated<Timestamp>
  flightId: string | null
  memberPackageId: number
  minutesUsed: number
  note: string | null
  usageId: Generated<number>
}

export interface ScheduleBookings {
  bookingId: string
  bookingStatus: BookingStatus
  bookingType: BookingType
  calendarSequence: Generated<number>
  cancellationNote: string | null
  cancellationReason: CancellationReason | null
  cancelledAt: Timestamp | null
  cancelledBy: string | null
  createdAt: Generated<Timestamp>
  createdBy: string
  description: string | null
  endTimeEpoch: Int8
  endTimeUtc: Generated<Timestamp>
  instructorMemberId: string | null
  memberId: string
  registration: string
  reminderSentAt: Timestamp | null
  startTimeEpoch: Int8
  startTimeUtc: Generated<Timestamp>
  updatedAt: Generated<Timestamp>
  updatedBy: string
}

export interface SchedulePushReminderLog {
  bookingId: string
  id: Generated<string>
  memberId: string
  sentAt: Generated<Timestamp>
}

export interface Secrets {
  createdAt: Generated<Timestamp>
  createdBy: string
  id: Generated<Int8>
  /**
   * Class of the secret: MEMBER (visible to all flying members) or BOARD (visible only to board members with admin access)
   */
  secretClass: Generated<SecretClassType>
  /**
   * The name/description of the secret (e.g., "Club house key code")
   */
  secretKey: string
  /**
   * The actual secret value (e.g., door code, combination)
   */
  secretValue: string
  updatedAt: Generated<Timestamp>
  updatedBy: string
}

export interface ShopCartItems {
  cartId: string
  cartItemId: Generated<number>
  createdAt: Generated<Timestamp>
  productId: string
  quantity: Generated<number>
  selectedOptions: Json | null
  updatedAt: Generated<Timestamp>
}

export interface ShopCarts {
  cartId: string
  createdAt: Generated<Timestamp>
  discountCodeId: number | null
  memberId: string
  updatedAt: Generated<Timestamp>
}

export interface ShopCategories {
  categoryId: string
  createdAt: Generated<Timestamp>
  createdBy: string
  description: Json | null
  isActive: Generated<boolean>
  name: Json
  sortOrder: Generated<number>
  updatedAt: Generated<Timestamp>
  updatedBy: string
}

export interface ShopDiscountCodeCategories {
  categoryId: string
  codeId: number
  createdAt: Generated<Timestamp>
}

export interface ShopDiscountCodes {
  code: string
  codeId: Generated<number>
  createdAt: Generated<Timestamp>
  createdBy: string
  description: string | null
  discountType: string
  discountValue: Numeric
  isActive: Generated<boolean>
  maxUses: number | null
  minOrderAmount: Numeric | null
  updatedAt: Generated<Timestamp>
  updatedBy: string
  usesCount: Generated<number>
  validFrom: Generated<Timestamp>
  validUntil: Timestamp | null
}

export interface ShopOrderItems {
  orderId: string
  orderItemId: Generated<number>
  productId: string
  productSnapshot: Json
  quantity: number
  selectedOptions: Json | null
  totalPrice: Numeric
  unitPrice: Numeric
}

export interface ShopOrders {
  createdAt: Generated<Timestamp>
  createdBy: string
  discountAmount: Numeric | null
  discountCodeId: number | null
  invoiceId: Int8 | null
  memberId: string
  notes: string | null
  orderId: string
  status: Generated<ShopOrderStatus>
  totalAmount: Numeric
  updatedAt: Generated<Timestamp>
  updatedBy: string
}

export interface ShopProductProperties {
  isRequired: Generated<boolean>
  name: Json
  productId: string
  propertyId: Generated<number>
  sortOrder: Generated<number>
}

export interface ShopProductPropertyOptions {
  isActive: Generated<boolean>
  optionId: Generated<number>
  propertyId: number
  sortOrder: Generated<number>
  stockQuantity: number | null
  value: Json
}

export interface ShopProducts {
  categoryId: string
  createdAt: Generated<Timestamp>
  createdBy: string
  description: Json | null
  imageUrl: string | null
  isActive: Generated<boolean>
  isPublished: Generated<boolean>
  lowStockThreshold: number | null
  maxOrderQuantity: number | null
  metadata: Json | null
  name: Json
  price: Numeric
  productId: string
  productType: Generated<ShopProductType>
  simplbooksItemId: string | null
  stockQuantity: Generated<number>
  tags: Generated<string[]>
  updatedAt: Generated<Timestamp>
  updatedBy: string
  vatPercent: Generated<Numeric>
}

export interface StaticAirfields {
  closed: boolean | null
  ident: string
  isoCountry: string | null
  name: string | null
}

export interface StaticUsefulPhoneNumber {
  label: string
  phoneNumber: string
  sortOrder: Generated<number>
}

export interface StatsAirfieldEfficiencyByAcYr {
  aircraftRegistration: string | null
  awayMins: Numeric | null
  efficiencyPct: Numeric | null
  efnuEfnuMins: Numeric | null
  inboundOutboundMins: Numeric | null
  totalFlightMins: Numeric | null
  totalReservedMins: Numeric | null
  yr: Numeric | null
}

export interface StatsAirfieldEfficiencyByAcYrMth {
  aircraftRegistration: string | null
  awayMins: Numeric | null
  efficiencyPct: Numeric | null
  efnuEfnuMins: Numeric | null
  inboundOutboundMins: Numeric | null
  mth: Numeric | null
  totalFlightMins: Numeric | null
  totalReservedMins: Numeric | null
  yr: Numeric | null
}

export interface StatsAirfieldEfficiencyByYr {
  awayMins: Numeric | null
  efficiencyPct: Numeric | null
  efnuEfnuMins: Numeric | null
  inboundOutboundMins: Numeric | null
  totalFlightMins: Numeric | null
  totalReservedMins: Numeric | null
  yr: Numeric | null
}

export interface StatsAirfieldEfficiencyByYrMth {
  awayMins: Numeric | null
  efficiencyPct: Numeric | null
  efnuEfnuMins: Numeric | null
  inboundOutboundMins: Numeric | null
  mth: Numeric | null
  totalFlightMins: Numeric | null
  totalReservedMins: Numeric | null
  yr: Numeric | null
}

export interface StatsAogDaysByAcDt {
  aircraftRegistration: string | null
  date: string | null
  reason: string | null
}

export interface StatsAogDaysByAcYr {
  aircraftRegistration: string | null
  maintenanceDays: Numeric | null
  totalAogDays: Numeric | null
  unserviceableDays: Numeric | null
  yr: Numeric | null
}

export interface StatsAogDaysByAcYrMth {
  aircraftRegistration: string | null
  maintenanceDays: Int8 | null
  mth: Numeric | null
  totalAogDays: Int8 | null
  unserviceableDays: Int8 | null
  yr: Numeric | null
}

export interface StatsAogIntervals {
  aircraftRegistration: string | null
  fromTs: Timestamp | null
  reason: string | null
  toTs: Timestamp | null
}

export interface StatsDtoTotalFlightTimeByAc {
  aircraftRegistration: string
  date: string
  flightType: string
  totalFlightMins: number
  totalIfrMins: number
  totalNfMins: number
}

export interface StatsDtoTotalFlightTimeByAcYr {
  aircraftRegistration: string
  flightType: string
  totalFlightMins: number
  totalIfrMins: number
  totalNfMins: number
  yr: number
}

export interface StatsDtoTotalFlightTimeByAcYrMth {
  aircraftRegistration: string
  flightType: string
  mth: number
  totalFlightMins: number
  totalIfrMins: number
  totalNfMins: number
  yr: number
}

export interface StatsLongestShortestAvgFlightByAcYr {
  aircraftRegistration: string
  averageFlight: number
  longestFlight: number
  medianFlight: number
  shortestFlight: number
  yr: number
}

export interface StatsMemberCountByType {
  memberCount: number
  memberType: string
}

export interface StatsNonBillableTotalFlightTimeByAc {
  aircraftRegistration: string
  date: string
  flightType: string
  totalFlightMins: number
  totalIfrMins: number
  totalNfMins: number
}

export interface StatsNonBillableTotalFlightTimeByAcYr {
  aircraftRegistration: string
  flightType: string
  totalFlightMins: number
  totalIfrMins: number
  totalNfMins: number
  yr: number
}

export interface StatsNonBillableTotalFlightTimeByAcYrMth {
  aircraftRegistration: string
  flightType: string
  mth: number
  totalFlightMins: number
  totalIfrMins: number
  totalNfMins: number
  yr: number
}

export interface StatsOccurrencesPer100hByAcYr {
  aircraftRegistration: string | null
  occurrenceCount: Int8 | null
  occurrencesPer100h: Numeric | null
  totalFlightMins: Int8 | null
  yr: Numeric | null
}

export interface StatsPobDistributionByAcYr {
  aircraftRegistration: string | null
  crossCountryFlightCount: Int8 | null
  flightCount: Int8 | null
  pobBucket: string | null
  totalFlightMins: Int8 | null
  yr: Numeric | null
}

export interface StatsReservationEfficiencyByAcYr {
  aircraftRegistration: string | null
  efficiencyPct: Numeric | null
  totalFlightMins: Numeric | null
  totalReservedMins: Numeric | null
  yr: Numeric | null
}

export interface StatsReservationEfficiencyByAcYrMth {
  aircraftRegistration: string | null
  efficiencyPct: Numeric | null
  mth: Numeric | null
  totalFlightMins: Numeric | null
  totalReservedMins: Numeric | null
  yr: Numeric | null
}

export interface StatsReservationEfficiencyByMemberYr {
  efficiencyPct: Numeric | null
  member: string | null
  totalFlightMins: Numeric | null
  totalReservedMins: Numeric | null
  yr: Numeric | null
}

export interface StatsReservationEfficiencyByMemberYrMth {
  efficiencyPct: Numeric | null
  member: string | null
  mth: Numeric | null
  totalFlightMins: Numeric | null
  totalReservedMins: Numeric | null
  yr: Numeric | null
}

export interface StatsReservationEfficiencyByYr {
  efficiencyPct: Numeric | null
  totalFlightMins: Numeric | null
  totalReservedMins: Numeric | null
  yr: Numeric | null
}

export interface StatsReservationEfficiencyByYrMth {
  efficiencyPct: Numeric | null
  mth: Numeric | null
  totalFlightMins: Numeric | null
  totalReservedMins: Numeric | null
  yr: Numeric | null
}

export interface StatsSchoolFlightEfficiencyByAcYr {
  aircraftRegistration: string | null
  efficiencyPct: Numeric | null
  totalBlockMins: Numeric | null
  totalReservedMins: Numeric | null
  yr: Numeric | null
}

export interface StatsSchoolFlightEfficiencyByAcYrMth {
  aircraftRegistration: string | null
  efficiencyPct: Numeric | null
  mth: Numeric | null
  totalBlockMins: Numeric | null
  totalReservedMins: Numeric | null
  yr: Numeric | null
}

export interface StatsSchoolFlightEfficiencyByInstructorYr {
  efficiencyPct: Numeric | null
  instructor: string | null
  totalBlockMins: Numeric | null
  totalReservedMins: Numeric | null
  yr: Numeric | null
}

export interface StatsSchoolFlightEfficiencyByInstructorYrMth {
  efficiencyPct: Numeric | null
  instructor: string | null
  mth: Numeric | null
  totalBlockMins: Numeric | null
  totalReservedMins: Numeric | null
  yr: Numeric | null
}

export interface StatsSchoolFlightEfficiencyByYr {
  efficiencyPct: Numeric | null
  totalBlockMins: Numeric | null
  totalReservedMins: Numeric | null
  yr: Numeric | null
}

export interface StatsSchoolFlightEfficiencyByYrMth {
  efficiencyPct: Numeric | null
  mth: Numeric | null
  totalBlockMins: Numeric | null
  totalReservedMins: Numeric | null
  yr: Numeric | null
}

export interface StatsTotalCommercialFlightTimeByAcYrMth {
  aircraftRegistration: string
  mth: number
  totalCommercialFlightMins: number
  yr: number
}

export interface StatsTotalFlightTimeByAcDt {
  aircraftRegistration: string
  date: string
  totalFlightMins: number
}

export interface StatsTotalFlightTimeByAcFt {
  aircraftRegistration: string
  date: string
  flightType: string
  totalFlightMins: number
  totalIfrMins: number
  totalNfMins: number
}

export interface StatsTotalFlightTimeByAcYr {
  aircraftRegistration: string | null
  totalFlightMins: Int8 | null
  yr: Numeric | null
}

export interface StatsTotalFlightTimeByAcYrFt {
  aircraftRegistration: string
  flightType: string
  totalFlightMins: number
  totalIfrMins: number
  totalNfMins: number
  yr: number
}

export interface StatsTotalFlightTimeByAcYrMthFt {
  aircraftRegistration: string
  flightType: string
  mth: number
  totalFlightMins: number
  totalIfrMins: number
  totalNfMins: number
  yr: number
}

export interface StatsTotalFlightTimeByPilot {
  date: string
  pilot: string
  totalFlightMins: number
  totalIfrMins: number
  totalNfMins: number
}

export interface StatsTotalFlightTimeByPilotYr {
  pilot: string
  totalFlightMins: number
  totalIfrMins: number
  totalNfMins: number
  yr: number
}

export interface StatsTotalFlightTimeByPilotYrMth {
  mth: number
  pilot: string
  totalFlightMins: number
  totalIfrMins: number
  totalNfMins: number
  yr: number
}

export interface StatsTotalFuelUpliftByAcYrMth {
  aircraftRegistration: string
  mth: number
  totalFuelUplift: number
  yr: number
}

export interface StatsTotalLandingsByAcYr {
  aircraftRegistration: string
  totalLandings: number
  yr: number
}

export interface StatsTotalOilUpliftByAcYrMth {
  aircraftRegistration: string
  mth: number
  totalOilUplift: number
  yr: number
}

export interface StatsVisitedAirfieldsByAc {
  aircraftRegistration: string
  airfield: string
  totalVisits: number
  yr: number
}

export interface DB {
  'accts.aircraftPricing': AcctsAircraftPricing
  'accts.costCentre': AcctsCostCentre
  'accts.expenseCategory': AcctsExpenseCategory
  'accts.expenseClaim': AcctsExpenseClaim
  'accts.expenseClaimAttachment': AcctsExpenseClaimAttachment
  'accts.expenseClaimEditAudit': AcctsExpenseClaimEditAudit
  'accts.expenseClaimLineItem': AcctsExpenseClaimLineItem
  'accts.expenseClaimMessage': AcctsExpenseClaimMessage
  'accts.expenseMileageDetail': AcctsExpenseMileageDetail
  'accts.invoice': AcctsInvoice
  'accts.items': AcctsItems
  'accts.localFuelPrice': AcctsLocalFuelPrice
  'accts.mileageAllowance': AcctsMileageAllowance
  'accts.mileageHetuAccessAudit': AcctsMileageHetuAccessAudit
  'accts.outboxSimplbooks': AcctsOutboxSimplbooks
  'accts.recurringFeesProcessing': AcctsRecurringFeesProcessing
  'club.ameEditSuggestion': ClubAmeEditSuggestion
  'club.ameList': ClubAmeList
  'club.ameRating': ClubAmeRating
  'club.ameRemovalRequest': ClubAmeRemovalRequest
  'dto.flightItemOutcomes': DtoFlightItemOutcomes
  'dto.hilQueue': DtoHilQueue
  'dto.memberSyllabus': DtoMemberSyllabus
  'dto.syllabus': DtoSyllabus
  'dto.syllabusFlightAttempts': DtoSyllabusFlightAttempts
  'dto.syllabusFlightItems': DtoSyllabusFlightItems
  'dto.syllabusFlights': DtoSyllabusFlights
  'dto.trainingProgram': DtoTrainingProgram
  emtMessages: EmtMessages
  emtProcessors: EmtProcessors
  emtProjections: EmtProjections
  emtStreams: EmtStreams
  'exam.attemptAnswers': ExamAttemptAnswers
  'exam.attemptQuestions': ExamAttemptQuestions
  'exam.attempts': ExamAttempts
  'exam.choices': ExamChoices
  'exam.choiceTranslations': ExamChoiceTranslations
  'exam.exams': ExamExams
  'exam.examVersions': ExamExamVersions
  'exam.examVersionTranslations': ExamExamVersionTranslations
  'exam.questions': ExamQuestions
  'exam.questionTranslations': ExamQuestionTranslations
  'flight.aircraft': FlightAircraft
  'flight.aircraftCards': FlightAircraftCards
  'flight.aircraftDocumentExpiryNotifications': FlightAircraftDocumentExpiryNotifications
  'flight.aircraftDocumentsFiles': FlightAircraftDocumentsFiles
  'flight.aircraftHil': FlightAircraftHil
  'flight.aircraftHilAudit': FlightAircraftHilAudit
  'flight.aircraftHilExtension': FlightAircraftHilExtension
  'flight.aircraftHilExtensionAudit': FlightAircraftHilExtensionAudit
  'flight.aircraftJourneyLogBook': FlightAircraftJourneyLogBook
  'flight.aircraftLandingsBaseline': FlightAircraftLandingsBaseline
  'flight.aircraftNavdata': FlightAircraftNavdata
  'flight.defect': FlightDefect
  'flight.defectAudit': FlightDefectAudit
  'flight.flightCredits': FlightFlightCredits
  'flight.fuelTypes': FlightFuelTypes
  'flight.logs': FlightLogs
  'flight.logsAudit': FlightLogsAudit
  'flight.maintenanceNote': FlightMaintenanceNote
  'flight.maintenanceNoteAudit': FlightMaintenanceNoteAudit
  'flight.occurrenceAccess': FlightOccurrenceAccess
  'flight.occurrenceAttachments': FlightOccurrenceAttachments
  'flight.occurrences': FlightOccurrences
  'flight.remark': FlightRemark
  'flight.remarkAudit': FlightRemarkAudit
  'flight.vwAircraftGroundingStatus': FlightVwAircraftGroundingStatus
  'flight.vwAjlbLiveRows': FlightVwAjlbLiveRows
  'flight.vwAjlbLiveSequence': FlightVwAjlbLiveSequence
  'flight.vwFlightLogs': FlightVwFlightLogs
  'flight.vwFlightTimeTotals': FlightVwFlightTimeTotals
  flywayDataHistory: FlywayDataHistory
  flywaySchemaHistory: FlywaySchemaHistory
  fuelPricesContent: FuelPricesContent
  'inventory.auditLog': InventoryAuditLog
  'inventory.categories': InventoryCategories
  'inventory.items': InventoryItems
  'inventory.locations': InventoryLocations
  'member.annualFees': MemberAnnualFees
  'member.brevoCampaignArchiveState': MemberBrevoCampaignArchiveState
  'member.brevoSyncState': MemberBrevoSyncState
  'member.documents': MemberDocuments
  'member.documentTinyUrls': MemberDocumentTinyUrls
  'member.events': MemberEvents
  'member.eventTranslations': MemberEventTranslations
  'member.loginAttempts': MemberLoginAttempts
  'member.loginEvents': MemberLoginEvents
  'member.mailboxMessages': MemberMailboxMessages
  'member.meeting': MemberMeeting
  'member.meetingAttendance': MemberMeetingAttendance
  'member.meetingVote': MemberMeetingVote
  'member.meetingVoteCounter': MemberMeetingVoteCounter
  'member.memberToRoles': MemberMemberToRoles
  'member.nonRenewalActions': MemberNonRenewalActions
  'member.passkeys': MemberPasskeys
  'member.pendingEmailChanges': MemberPendingEmailChanges
  'member.pushSubscriptions': MemberPushSubscriptions
  'member.qualificationProofFiles': MemberQualificationProofFiles
  'member.register': MemberRegister
  'member.registerAudit': MemberRegisterAudit
  'member.roles': MemberRoles
  'member.simplbooksSyncState': MemberSimplbooksSyncState
  'member.voteCast': MemberVoteCast
  'member.voteOption': MemberVoteOption
  'member.voteSelection': MemberVoteSelection
  'member.webauthnChallenges': MemberWebauthnChallenges
  notificationBanner: NotificationBanner
  'prepaid.memberPackages': PrepaidMemberPackages
  'prepaid.packages': PrepaidPackages
  'prepaid.usageLog': PrepaidUsageLog
  'schedule.bookings': ScheduleBookings
  'schedule.pushReminderLog': SchedulePushReminderLog
  secrets: Secrets
  'shop.cartItems': ShopCartItems
  'shop.carts': ShopCarts
  'shop.categories': ShopCategories
  'shop.discountCodeCategories': ShopDiscountCodeCategories
  'shop.discountCodes': ShopDiscountCodes
  'shop.orderItems': ShopOrderItems
  'shop.orders': ShopOrders
  'shop.productProperties': ShopProductProperties
  'shop.productPropertyOptions': ShopProductPropertyOptions
  'shop.products': ShopProducts
  'static.airfields': StaticAirfields
  'static.usefulPhoneNumber': StaticUsefulPhoneNumber
  'stats.airfieldEfficiencyByAcYr': StatsAirfieldEfficiencyByAcYr
  'stats.airfieldEfficiencyByAcYrMth': StatsAirfieldEfficiencyByAcYrMth
  'stats.airfieldEfficiencyByYr': StatsAirfieldEfficiencyByYr
  'stats.airfieldEfficiencyByYrMth': StatsAirfieldEfficiencyByYrMth
  'stats.aogDaysByAcDt': StatsAogDaysByAcDt
  'stats.aogDaysByAcYr': StatsAogDaysByAcYr
  'stats.aogDaysByAcYrMth': StatsAogDaysByAcYrMth
  'stats.aogIntervals': StatsAogIntervals
  'stats.dtoTotalFlightTimeByAc': StatsDtoTotalFlightTimeByAc
  'stats.dtoTotalFlightTimeByAcYr': StatsDtoTotalFlightTimeByAcYr
  'stats.dtoTotalFlightTimeByAcYrMth': StatsDtoTotalFlightTimeByAcYrMth
  'stats.longestShortestAvgFlightByAcYr': StatsLongestShortestAvgFlightByAcYr
  'stats.memberCountByType': StatsMemberCountByType
  'stats.nonBillableTotalFlightTimeByAc': StatsNonBillableTotalFlightTimeByAc
  'stats.nonBillableTotalFlightTimeByAcYr': StatsNonBillableTotalFlightTimeByAcYr
  'stats.nonBillableTotalFlightTimeByAcYrMth': StatsNonBillableTotalFlightTimeByAcYrMth
  'stats.occurrencesPer100hByAcYr': StatsOccurrencesPer100hByAcYr
  'stats.pobDistributionByAcYr': StatsPobDistributionByAcYr
  'stats.reservationEfficiencyByAcYr': StatsReservationEfficiencyByAcYr
  'stats.reservationEfficiencyByAcYrMth': StatsReservationEfficiencyByAcYrMth
  'stats.reservationEfficiencyByMemberYr': StatsReservationEfficiencyByMemberYr
  'stats.reservationEfficiencyByMemberYrMth': StatsReservationEfficiencyByMemberYrMth
  'stats.reservationEfficiencyByYr': StatsReservationEfficiencyByYr
  'stats.reservationEfficiencyByYrMth': StatsReservationEfficiencyByYrMth
  'stats.schoolFlightEfficiencyByAcYr': StatsSchoolFlightEfficiencyByAcYr
  'stats.schoolFlightEfficiencyByAcYrMth': StatsSchoolFlightEfficiencyByAcYrMth
  'stats.schoolFlightEfficiencyByInstructorYr': StatsSchoolFlightEfficiencyByInstructorYr
  'stats.schoolFlightEfficiencyByInstructorYrMth': StatsSchoolFlightEfficiencyByInstructorYrMth
  'stats.schoolFlightEfficiencyByYr': StatsSchoolFlightEfficiencyByYr
  'stats.schoolFlightEfficiencyByYrMth': StatsSchoolFlightEfficiencyByYrMth
  'stats.totalCommercialFlightTimeByAcYrMth': StatsTotalCommercialFlightTimeByAcYrMth
  'stats.totalFlightTimeByAcDt': StatsTotalFlightTimeByAcDt
  'stats.totalFlightTimeByAcFt': StatsTotalFlightTimeByAcFt
  'stats.totalFlightTimeByAcYr': StatsTotalFlightTimeByAcYr
  'stats.totalFlightTimeByAcYrFt': StatsTotalFlightTimeByAcYrFt
  'stats.totalFlightTimeByAcYrMthFt': StatsTotalFlightTimeByAcYrMthFt
  'stats.totalFlightTimeByPilot': StatsTotalFlightTimeByPilot
  'stats.totalFlightTimeByPilotYr': StatsTotalFlightTimeByPilotYr
  'stats.totalFlightTimeByPilotYrMth': StatsTotalFlightTimeByPilotYrMth
  'stats.totalFuelUpliftByAcYrMth': StatsTotalFuelUpliftByAcYrMth
  'stats.totalLandingsByAcYr': StatsTotalLandingsByAcYr
  'stats.totalOilUpliftByAcYrMth': StatsTotalOilUpliftByAcYrMth
  'stats.visitedAirfieldsByAc': StatsVisitedAirfieldsByAc
}
