CREATE TABLE flight.aircraft_document_expiry_notifications (
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id         INT NOT NULL REFERENCES flight.aircraft_documents_files(document_id) ON DELETE CASCADE,
    notification_type   VARCHAR(10) NOT NULL CHECK (notification_type IN ('REMINDER', 'EXPIRED')),
    days_threshold      INT NOT NULL DEFAULT 0,
    sent_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (document_id, notification_type, days_threshold)
);

GRANT SELECT, INSERT ON flight.aircraft_document_expiry_notifications TO ${app_db_user};
GRANT USAGE, SELECT ON SEQUENCE flight.aircraft_document_expiry_notifications_id_seq TO ${app_db_user};
