-- Create enum for aircraft-specific document types
CREATE TYPE flight.aircraft_document_type AS ENUM (
    'ARC',
    'Noise Certificate',
    'Insurance Certificate',
    'Registration',
    'Radio Licence',
    'Transponder Mode S certificate',
    'Certificate of Airworthiness',
    'Weight Report',
    'Finavia Season card',
    'Checklist',
    'POH / AFM',
    'Maintenance Manual',
    'Other'
);
-- Create aircraft documents table for file-based documents
CREATE TABLE flight.aircraft_documents_files (
    document_id int GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_aircraft_documents_files PRIMARY KEY,
    aircraft_registration VARCHAR(10) NOT NULL REFERENCES flight.aircraft(registration) ON DELETE CASCADE,
    document_type flight.aircraft_document_type NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    document_url VARCHAR(500) NOT NULL,
    valid_from DATE,
    valid_to DATE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    -- File metadata
    file_name VARCHAR(255) NOT NULL,
    file_size INTEGER,
    mime_type VARCHAR(100),
    storage_key VARCHAR(500),
    -- Audit fields
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(9) NOT NULL REFERENCES member.register (member_id),
    updated_by VARCHAR(9) NOT NULL REFERENCES member.register (member_id)
);