CREATE TABLE flight.aircraft
(
    registration VARCHAR(10) UNIQUE NOT NULL PRIMARY KEY,
    display_name VARCHAR(50) NOT NULL,
    model VARCHAR(50) NOT NULL,
    manufacturer VARCHAR(50) NOT NULL,
    year_of_manufacture INT NOT NULL,
    seats INT NOT NULL,
    usable_fuel_litres INT NOT NULL,
    fuel_types VARCHAR(50)[] NOT NULL,
    active BOOLEAN NOT NULL DEFAULT FALSE,
    maintenance_cycle INT NOT NULL,
    last_maintenance_date DATE NOT NULL,
    last_maintenance_type VARCHAR(20) NOT NULL,
    last_maintenance_tach INT NOT NULL,
    next_maintenance_date DATE,
    next_maintenance_type VARCHAR(20) NOT NULL,
    next_maintenance_tach INT NOT NULL,
    total_percentage_hours INT NOT NULL,
    usable_percentage_hours INT NOT NULL,
    notes JSONB,
    location VARCHAR(255),
    equipment VARCHAR(255),
    hourly_rate_eur DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(9) NOT NULL REFERENCES member.register (member_id),
    updated_by VARCHAR(9) NOT NULL REFERENCES member.register (member_id)
);
