INSERT INTO flight.aircraft (
        registration,
        display_name,
        model,
        manufacturer,
        year_of_manufacture,
        seats,
        usable_fuel_litres,
        fuel_types,
        active,
        maintenance_cycle,
        last_maintenance_date,
        last_maintenance_type,
        last_maintenance_tach,
        next_maintenance_date,
        next_maintenance_type,
        next_maintenance_tach,
        total_percentage_hours,
        usable_percentage_hours,
        notes,
        "location",
        equipment,
        hourly_rate_eur,
        image_url,
        created_at,
        updated_at,
        created_by,
        updated_by
    )
VALUES(
        'OH-STL',
        'Diamond DA40',
        'DA40',
        'Diamond Aircraft',
        2007,
        4,
        148,
        '{JETA-1}',
        true,
        100,
        '2024-11-10',
        '200h',
        4709,
        NULL,
        '100h',
        4778,
        10,
        8,
        '[{"text": "Keep oil quantity level in the middle of the approved range - do not add to full!", "severity": "note"}]'::jsonb,
        'EFNU BF-hangar 21',
        'SDFGY/S',
        216.00,
        'https://www.flyfinland.fi/photos/original/29416.jpg',
        '2025-11-17 13:17:41.64235',
        '2025-11-17 13:17:41.64235',
        'k1mnimda',
        'k1mnimda'
    ) ON CONFLICT (registration) DO NOTHING;
INSERT INTO flight.aircraft (
        registration,
        display_name,
        model,
        manufacturer,
        year_of_manufacture,
        seats,
        usable_fuel_litres,
        fuel_types,
        active,
        maintenance_cycle,
        last_maintenance_date,
        last_maintenance_type,
        last_maintenance_tach,
        next_maintenance_date,
        next_maintenance_type,
        next_maintenance_tach,
        total_percentage_hours,
        usable_percentage_hours,
        notes,
        "location",
        equipment,
        hourly_rate_eur,
        image_url,
        created_at,
        updated_at,
        created_by,
        updated_by
    )
VALUES(
        'OH-IHQ',
        'Diamond DV20',
        'DV20',
        'Diamond Aircraft',
        2010,
        2,
        77,
        '{AVGAS,MOGAS}',
        true,
        50,
        '2025-03-01',
        '200h',
        6085,
        NULL,
        '50h',
        6130,
        5,
        3,
        '[{"text": "Koneen palosammutin on huollossa. Ei ole pakollinen varuste, mutta huomioitava!", "severity": "caution"}]'::jsonb,
        'EFNU Cumulus Hangar',
        'VOY/S',
        147.00,
        'https://cdn.jetphotos.com/full/5/69415_1600241420.jpg',
        '2025-11-17 13:17:41.64235',
        '2025-11-17 13:17:41.64235',
        'k1mnimda',
        'k1mnimda'
    ) ON CONFLICT (registration) DO NOTHING;