

GRANT CONNECT ON DATABASE ${mik_db_name} TO ${app_db_user};



-- Grant schema access on all schemas
GRANT USAGE ON SCHEMA public, member, flight, static, accts, schedule TO ${app_db_user};

-- Grant table permissions on all schemas
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${app_db_user};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA member TO ${app_db_user};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA flight TO ${app_db_user};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA static TO ${app_db_user};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA accts TO ${app_db_user};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA schedule TO ${app_db_user};

-- Grant sequence permissions on all schemas
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ${app_db_user};
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA member TO ${app_db_user};
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA flight TO ${app_db_user};
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA static TO ${app_db_user};
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA accts TO ${app_db_user};
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA schedule TO ${app_db_user};

-- Grant default privileges for future tables
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${app_db_user};
ALTER DEFAULT PRIVILEGES IN SCHEMA member GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${app_db_user};
ALTER DEFAULT PRIVILEGES IN SCHEMA flight GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${app_db_user};
ALTER DEFAULT PRIVILEGES IN SCHEMA static GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${app_db_user};
ALTER DEFAULT PRIVILEGES IN SCHEMA accts GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${app_db_user};
ALTER DEFAULT PRIVILEGES IN SCHEMA schedule GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${app_db_user};

-- Grant default privileges for future sequences
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO ${app_db_user};
ALTER DEFAULT PRIVILEGES IN SCHEMA member GRANT USAGE, SELECT ON SEQUENCES TO ${app_db_user};
ALTER DEFAULT PRIVILEGES IN SCHEMA flight GRANT USAGE, SELECT ON SEQUENCES TO ${app_db_user};
ALTER DEFAULT PRIVILEGES IN SCHEMA static GRANT USAGE, SELECT ON SEQUENCES TO ${app_db_user};
ALTER DEFAULT PRIVILEGES IN SCHEMA accts GRANT USAGE, SELECT ON SEQUENCES TO ${app_db_user};
ALTER DEFAULT PRIVILEGES IN SCHEMA schedule GRANT USAGE, SELECT ON SEQUENCES TO ${app_db_user};