GRANT USAGE ON SCHEMA stats TO ${app_db_user};

GRANT SELECT, INSERT, UPDATE, DELETE
    ON ALL TABLES IN SCHEMA stats
    TO ${app_db_user};

GRANT USAGE, SELECT
    ON ALL SEQUENCES IN SCHEMA stats
    TO ${app_db_user};

ALTER DEFAULT PRIVILEGES IN SCHEMA stats
    GRANT SELECT, INSERT, UPDATE, DELETE
    ON TABLES
    TO ${app_db_user};

ALTER DEFAULT PRIVILEGES IN SCHEMA stats
    GRANT USAGE, SELECT
    ON SEQUENCES
    TO ${app_db_user};