-- Create aircraft cards table for non-document expiring/seasonal mandatory data
-- Examples: fuel cards (Air BP, Kanair), season cards (EFNU, Kiikala, Finavia)
CREATE TABLE flight.aircraft_cards (
    card_id INT GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_aircraft_cards PRIMARY KEY,
    aircraft_registration VARCHAR(10) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    valid_from DATE,
    valid_to DATE,
    -- Audit fields
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(9) NOT NULL,
    updated_by VARCHAR(9) NOT NULL,
    -- Foreign keys
    CONSTRAINT fk_aircraft_cards_aircraft FOREIGN KEY (aircraft_registration)
        REFERENCES flight.aircraft (registration) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_aircraft_cards_created_by FOREIGN KEY (created_by)
        REFERENCES member.register (member_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_aircraft_cards_updated_by FOREIGN KEY (updated_by)
        REFERENCES member.register (member_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT chk_aircraft_cards_valid_dates CHECK (valid_from IS NULL OR valid_to IS NULL OR valid_from <= valid_to)
);

-- Grant permissions to application user
GRANT SELECT, INSERT, UPDATE, DELETE ON flight.aircraft_cards TO ${app_db_user};
GRANT USAGE, SELECT ON SEQUENCE flight.aircraft_cards_card_id_seq TO ${app_db_user};
