import { z, ZodObject } from 'zod'

import { AuditableSchema, BigintAsString, BooleanSchema, UpsertSchema } from '../../types/schema.ts'

export const CrewRoleEnum = z.enum(['FE', 'FI', 'OBS', 'PIC', 'STU'])
export const PrivOrComFlightEnum = z.enum(['P', 'C'])
export type PrivOrComFlight = z.infer<typeof PrivOrComFlightEnum>

export enum FlightLogStatus {
  NEW = 'NEW',
  VALIDATED = 'VALIDATED',
  INVOICED = 'INVOICED',
  PAID = 'PAID',
}

export enum FlightType {
  // currently valid types

  // 1: Harjoituslento
  // 5: Yö harjoituslento
  PRIVATE = 'PRIVATE',

  // 2: 'Koululento',
  // 4: Koulumatkalento
  // 7: Yö Koululento
  // 8: Yö Koulumatkalento
  // 11: Kertauskoululento
  SCHOOL = 'SCHOOL',
  DTO = 'DTO',

  // 16: SAR tehtävä
  // 17: SAR koulutus
  SAR = 'SAR',

  // legacy types
  // 3: Matkalento
  // 6: Yö Matkalento
  XC = 'XC',
  // 9: Välitarkastuslento
  // 10: Tarkastuslento
  CHECKFLIGHT = 'CHECKFLIGHT',
  // 12: Siirtolento
  FERRY = 'FERRY',
  // 13: Taitolento
  AEROBATICS = 'AEROBATICS',
  // 14: Muu (tarkenna huomautuksiin)
  OTHER = 'OTHER',
  // 18: Koelento
  TEST_FLIGHT = 'TEST_FLIGHT',
}

export const FlightLogFiltersSchema = z
  .object({
    flightId: z.string().optional(),
    billableMemberId: z.string().optional(),
    aircraftRegistration: z.string().optional(),
    ajlbSeqNo: z.coerce.number().int().optional(),
    pic: z.string().optional(),
    crew2: z.string().optional(),
    crew3: z.string().optional(),
    crew4: z.string().optional(),
    startDate: z.string().datetime().optional(),
    endDate: z.string().datetime().optional(),
    status: z.nativeEnum(FlightLogStatus).optional(),
    page: z.coerce.number().int().optional(),
    limit: z.coerce.number().int().optional(),
    orderLatestFirst: BooleanSchema.optional(),
    incidentsOrObservations: BooleanSchema.optional(),
  })
  .strict()

// Type inference from the schema (should match your interface)
export type FlightLogFilters = z.infer<typeof FlightLogFiltersSchema>

export const FlightLogSchema = AuditableSchema.extend({
  acTotalFlightTime: z.string().nullable().readonly(),
  aircraftRegistration: z.string(),
  ajlbBlankRowsBefore: z.number().int().min(0),
  ajlbSeqNo: z.number().int().positive(),
  ajlbPageNo: z.number().int().positive(),
  ajlbRowNo: z.number().int().positive().readonly(),
  arrivalAirport: z.string(),
  billableMemberId: z.string(),
  billingRemarks: z.string().nullable(),
  blockMins: z.number().readonly(),
  blockTime: z.string().readonly(),
  crew2LastName: z.string().nullable().readonly(),
  crew2MemberId: z.string().nullable(),
  crew2Role: CrewRoleEnum.nullable(),
  crew3LastName: z.string().nullable().readonly(),
  crew3MemberId: z.string().nullable(),
  crew3Role: CrewRoleEnum.nullable(),
  crew4LastName: z.string().nullable().readonly(),
  crew4MemberId: z.string().nullable(),
  crew4Role: CrewRoleEnum.nullable(),
  departureAirport: z.string(),
  flightId: z.string().readonly(),
  flightMins: z.number().readonly(),
  flightTime: z.string().readonly(),
  flightType: z.nativeEnum(FlightType),
  fuelRemainingLitres: z.number().positive(),
  fuelUpliftLitres: z.number().min(0).nullable(),
  incidentOrObservations: z.string().nullable(),
  instrumentFlyingMins: z.number().int().min(0),
  invoiceNumber: z.string().nullable(),
  isBillableFlight: z.boolean(),
  isDtoTrainingFlight: z.boolean(),
  isBilled: z.boolean().readonly(),
  nightFlyingMins: z.number().int().min(0),
  nonBillingApprovedByMemberId: z.string().nullable(),
  nonBillingReason: z.string().nullable(),
  numberOfLandings: z.number().int().min(0),
  numberOfNightLandings: z.number().int().min(0),
  oilUpliftLitres: z.number().min(0).nullable(),
  offBlockTimeEpoch: BigintAsString,
  offBlockTimeUtc: z.string().datetime().readonly(),
  takeoffTimeEpoch: BigintAsString,
  takeoffTimeUtc: z.string().datetime().readonly(),
  landingTimeEpoch: BigintAsString,
  landingTimeUtc: z.string().datetime().readonly(),
  onBlockTimeEpoch: BigintAsString,
  onBlockTimeUtc: z.string().datetime().readonly(),
  personalRemarks: z.string().nullable(),
  personsOnBoard: z.number().int().min(1).max(4),
  picLastName: z.string().readonly(),
  picMemberId: z.string(),
  picRole: CrewRoleEnum,
  privOrComFlight: PrivOrComFlightEnum,
  status: z.nativeEnum(FlightLogStatus),
  totalTimeInService: z.number().nullable(),
})

// All editable fields which are not generated by the database
export const FlightLogUpsertSchema = UpsertSchema(FlightLogSchema).pick({
  aircraftRegistration: true,
  ajlbBlankRowsBefore: true,
  ajlbSeqNo: true,
  arrivalAirport: true,
  billableMemberId: true,
  billingRemarks: true,
  crew2MemberId: true,
  crew2Role: true,
  crew3MemberId: true,
  crew3Role: true,
  crew4MemberId: true,
  crew4Role: true,
  departureAirport: true,
  flightType: true,
  fuelRemainingLitres: true,
  fuelUpliftLitres: true,
  incidentOrObservations: true,
  instrumentFlyingMins: true,
  isBillableFlight: true,
  nightFlyingMins: true,
  nonBillingReason: true,
  numberOfLandings: true,
  numberOfNightLandings: true,
  oilUpliftLitres: true,
  offBlockTimeEpoch: true,
  takeoffTimeEpoch: true,
  landingTimeEpoch: true,
  onBlockTimeEpoch: true,
  personalRemarks: true,
  personsOnBoard: true,
  picMemberId: true,
  picRole: true,
  totalTimeInService: true,
})

// extra raw fields needed for migration
export const FlightLogMigrationSchema = FlightLogSchema.pick({
  isBillableFlight: true,
  isDtoTrainingFlight: true,
  invoiceNumber: true,
}).merge(FlightLogUpsertSchema)

export type FlightLogMigrationRequest = z.infer<typeof FlightLogMigrationSchema>

// Regular members cannot edit all fields
export const FlightLogMemberUpsertSchema = FlightLogUpsertSchema.omit({
  ajlbBlankRowsBefore: true,
  ajlbSeqNo: true,
  billableMemberId: true,
  isBillableFlight: true,
  nonBillingReason: true,
})

// Editable fields after validation
export const ValidatedFlightLogAdminUpsertSchema = FlightLogUpsertSchema.pick({
  billableMemberId: true,
  billingRemarks: true,
  isBillableFlight: true,
  nonBillingReason: true,
  personalRemarks: true,
})
export const ValidatedFlightLogMemberUpsertSchema = FlightLogUpsertSchema.pick({
  billingRemarks: true,
  personalRemarks: true,
})

// Editable fields after billing
export const BilledFlightLogUpsertSchema = FlightLogUpsertSchema.pick({
  personalRemarks: true,
})

export const FlightLogTimesSchema = z.object({
  offBlockTimeEpoch: BigintAsString,
  takeoffTimeEpoch: BigintAsString,
  landingTimeEpoch: BigintAsString,
  onBlockTimeEpoch: BigintAsString,
})

type FlightLogTimes = z.infer<typeof FlightLogTimesSchema>

export const validateFlightLogTimes = (
  times: Partial<FlightLogTimes>,
  addIssue: (i: z.IssueData) => void,
) => {
  const validate = (
    prevKey: keyof FlightLogTimes,
    nextKey: keyof FlightLogTimes,
    minutes: number,
  ) => {
    if (times[prevKey] && times[nextKey]) {
      const prev = Number(times[prevKey])
      const next = Number(times[nextKey])

      // check the correct order
      if (next <= prev) {
        addIssue({
          code: z.ZodIssueCode.too_small,
          minimum: prev,
          inclusive: false,
          message: prev.toString(),
          type: 'bigint',
          path: [nextKey],
        })
      }

      // check limit how long the block can be
      const maximum = prev + minutes * 60
      if (next > maximum) {
        addIssue({
          code: z.ZodIssueCode.too_big,
          maximum,
          message: maximum.toString(),
          inclusive: true,
          type: 'bigint',
          path: [nextKey],
        })
      }
    }
  }

  // taxi out is limited to 1 hour
  validate('offBlockTimeEpoch', 'takeoffTimeEpoch', 60)

  // flight max 6 hours
  validate('takeoffTimeEpoch', 'landingTimeEpoch', 360)

  // taxi in is limited to 30 minutes
  validate('landingTimeEpoch', 'onBlockTimeEpoch', 30)
}

export const flightLogDateValidator = <T extends ZodObject<typeof FlightLogTimesSchema.shape>>(
  schema: T,
) =>
  // Zod's refine doesn't work unless all fields are valid.
  // Use preprocessor instead to get error messages shown in the UI with incomplete form.
  // https://github.com/colinhacks/zod/issues/479#issuecomment-2429834215
  z.preprocess((input, ctx) => {
    const parsed = schema
      .pick({
        offBlockTimeEpoch: true,
        takeoffTimeEpoch: true,
        landingTimeEpoch: true,
        onBlockTimeEpoch: true,
      })
      .strip()
      .partial()
      .safeParse(input)

    if (parsed.success) {
      validateFlightLogTimes(parsed.data, ctx.addIssue)
    }
    return input
  }, schema)

// Infer the TypeScript type from the Zod schema
export type FlightLog = z.infer<typeof FlightLogSchema>
export type FlightLogUpsertRequest = z.infer<typeof FlightLogUpsertSchema>
export type FlightLogMemberRequest = z.infer<typeof FlightLogMemberUpsertSchema>

export const FlightLogValidationRequestSchema = z.object({
  revert: z.boolean().optional(),
})

export type FlightLogValidationRequest = z.infer<typeof FlightLogValidationRequestSchema>

export const FlightLogListEntrySchema = FlightLogSchema.pick({
  acTotalFlightTime: true,
  aircraftRegistration: true,
  ajlbBlankRowsBefore: true,
  ajlbSeqNo: true,
  ajlbRowNo: true,
  arrivalAirport: true,
  billableMemberId: true,
  blockTime: true,
  crew2LastName: true,
  departureAirport: true,
  flightId: true,
  flightTime: true,
  flightType: true,
  fuelRemainingLitres: true,
  fuelUpliftLitres: true,
  incidentOrObservations: true,
  instrumentFlyingMins: true,
  nightFlyingMins: true,
  numberOfLandings: true,
  numberOfNightLandings: true,
  oilUpliftLitres: true,
  offBlockTimeUtc: true,
  takeoffTimeUtc: true,
  landingTimeUtc: true,
  onBlockTimeUtc: true,
  personsOnBoard: true,
  picLastName: true,
  status: true,
  totalTimeInService: true,
})

export type FlightLogListEntry = z.infer<typeof FlightLogListEntrySchema>

export const FlightLogListResponseSchema = z.object({
  logs: z.array(FlightLogListEntrySchema),
  page: z.number().int().optional(),
  limit: z.number().int().optional(),
  pages: z.number().int().optional(),
  rows: z.number().int().optional(),
})

export type FlightLogListResponse = z.infer<typeof FlightLogListResponseSchema>

export const FlightTimeTotalsSchema = z.object({
  aircraftRegistration: z.string(),
  ajlbSeqNo: z.number().int(),
  acTotalFlightTime: z.string(),
  acTotalFlightHours: z.number(),
})

export type FlightTimeTotals = z.infer<typeof FlightTimeTotalsSchema>

export const AirfieldListResponseSchema = z.object({
  airfields: z.array(
    z.object({
      ident: z.string(),
      name: z.string(),
      country: z.string(),
    }),
  ),
})

export type AirfieldListResponse = z.infer<typeof AirfieldListResponseSchema>

export enum InvoicableFlights {
  FERRY = 'FERRY',
  TEST_FLIGHT = 'TEST_FLIGHT',
  COMMENT = 'COMMENT',
  OTHER = 'OTHER',
}

export const InvoicableFlightFiltersSchema = z
  .object({
    aircraftRegistration: z.string(),
    endDate: z.string().date(),
    flights: z.nativeEnum(InvoicableFlights).optional(),
    page: z.coerce.number().int().optional(),
    limit: z.coerce.number().int().optional(),
  })
  .strict()

export type InvoicableFlightFilters = z.infer<typeof InvoicableFlightFiltersSchema>

export const InvoicableFlightSchema = FlightLogSchema.pick({
  aircraftRegistration: true,
  arrivalAirport: true,
  billableMemberId: true,
  billingRemarks: true,
  departureAirport: true,
  flightId: true,
  flightTime: true,
  flightMins: true,
  blockMins: true,
  blockTime: true,
  flightType: true,
  fuelUpliftLitres: true,
  isBillableFlight: true,
  numberOfLandings: true,
  takeoffTimeUtc: true,
  landingTimeUtc: true,
  personsOnBoard: true,
  picLastName: true,
  status: true,
}).extend({
  billableMemberLastName: z.string().nullable().readonly(),
  isTrainingProgramPilot: z.boolean().nullable().readonly(),
  billingId: z.string().nullable().readonly(),
})

export type InvoicableFlight = z.infer<typeof InvoicableFlightSchema>

export const FlightInvoicePayloadSchema = z.object({
  flights: z.array(InvoicableFlightSchema),
})

export type FlightInvoicePayload = z.infer<typeof FlightInvoicePayloadSchema>

export const InvoicableFlightListResponseSchema = z.object({
  logs: z.array(InvoicableFlightSchema),
  page: z.number().int().optional(),
  limit: z.number().int().optional(),
  pages: z.number().int().optional(),
  rows: z.number().int().optional(),
})

export type InvoicableFlightListResponse = z.infer<typeof InvoicableFlightListResponseSchema>

export const InvoiceFlightsSchema = z
  .object({
    aircraftRegistration: z.string(),
    endDate: z.string().date(),
  })
  .strict()

export type InvoiceFlights = z.infer<typeof InvoiceFlightsSchema>
