import { z, ZodObject } from 'zod'

import { AuditableSchema, BooleanSchema, UpsertSchema } from '../../types/schema.ts'

export const CrewRoleEnum = z.enum(['FE', 'FI', 'OBS', 'PIC', 'STU'])
export const PrivOrComFlightEnum = z.enum(['P', 'C'])

export enum FlightLogStatus {
  NEW = 'NEW',
  VALIDATED = 'VALIDATED',
  INVOICED = 'INVOICED',
  PAID = 'PAID',
}

const bigintAsString = z.string().regex(/^\d+$/)

export const FlightLogFiltersSchema = z
  .object({
    flightId: z.string().optional(),
    billableMemberId: z.string().optional(),
    aircraftRegistration: z.string().optional(),
    ajlbSeqNo: z.coerce.number().int().optional(),
    pic: z.string().optional(),
    crew2: z.string().optional(),
    crew3: z.string().optional(),
    crew4: z.string().optional(),
    startDate: z.string().datetime().optional(),
    endDate: z.string().datetime().optional(),
    status: z.nativeEnum(FlightLogStatus).optional(),
    page: z.coerce.number().int().optional(),
    limit: z.coerce.number().int().optional(),
    orderLatestFirst: BooleanSchema.optional(),
  })
  .strict()

// Type inference from the schema (should match your interface)
export type FlightLogFilters = z.infer<typeof FlightLogFiltersSchema>

export const FlightLogSchema = AuditableSchema.extend({
  acTotalFlightTime: z.string().nullable().readonly(),
  aircraftRegistration: z.string(),
  ajlbBlankRowsBefore: z.number().int().min(0),
  ajlbSeqNo: z.number().int().positive(),
  arrivalAirport: z.string(),
  billableMemberId: z.string(),
  billingRemarks: z.string().nullable(),
  blockMins: z.number().readonly(),
  blockTime: z.string().readonly(),
  crew2LastName: z.string().nullable().readonly(),
  crew2MemberId: z.string().nullable(),
  crew2Role: CrewRoleEnum.nullable(),
  crew3MemberId: z.string().nullable(),
  crew3Role: CrewRoleEnum.nullable(),
  crew4MemberId: z.string().nullable(),
  crew4Role: CrewRoleEnum.nullable(),
  departureAirport: z.string(),
  flightId: z.string().readonly(),
  flightMins: z.number().readonly(),
  flightTime: z.string().readonly(),
  flightType: z.string(),
  fuelRemainingLitres: z.number().positive(),
  fuelUpliftLitres: z.number().min(0).nullable(),
  incidentOrObservations: z.string().nullable(),
  instrumentFlyingMins: z.number().int().min(0),
  invoiceNumber: z.string().nullable(),
  isBillableFlight: z.boolean(),
  isDtoTrainingFlight: z.boolean(),
  isBilled: z.boolean().readonly(),
  nightFlyingMins: z.number().int().min(0),
  nonBillingApprovedByMemberId: z.string().nullable(),
  nonBillingReason: z.string().nullable(),
  numberOfLandings: z.number().int().min(0),
  numberOfNightLandings: z.number().int().min(0),
  oilUpliftLitres: z.number().min(0).nullable(),
  offBlockTimeEpoch: bigintAsString,
  offBlockTimeUtc: z.string().datetime().readonly(),
  takeoffTimeEpoch: bigintAsString,
  takeoffTimeUtc: z.string().datetime().readonly(),
  landingTimeEpoch: bigintAsString,
  landingTimeUtc: z.string().datetime().readonly(),
  onBlockTimeEpoch: bigintAsString,
  onBlockTimeUtc: z.string().datetime().readonly(),
  personalRemarks: z.string().nullable(),
  personsOnBoard: z.number().int().min(1).max(4),
  picLastName: z.string().readonly(),
  picMemberId: z.string(),
  picRole: CrewRoleEnum,
  privOrComFlight: z.string(),
  status: z.nativeEnum(FlightLogStatus),
  totalTimeInService: z.number().nullable(),
})

// All editable fields which are not generated by the database
export const FlightLogUpsertSchema = UpsertSchema(FlightLogSchema).pick({
  aircraftRegistration: true,
  ajlbBlankRowsBefore: true,
  ajlbSeqNo: true,
  arrivalAirport: true,
  billableMemberId: true,
  billingRemarks: true,
  crew2MemberId: true,
  crew2Role: true,
  crew3MemberId: true,
  crew3Role: true,
  crew4MemberId: true,
  crew4Role: true,
  departureAirport: true,
  flightType: true,
  fuelRemainingLitres: true,
  fuelUpliftLitres: true,
  incidentOrObservations: true,
  instrumentFlyingMins: true,
  invoiceNumber: true,
  isBillableFlight: true,
  nightFlyingMins: true,
  nonBillingApprovedByMemberId: true,
  nonBillingReason: true,
  numberOfLandings: true,
  numberOfNightLandings: true,
  oilUpliftLitres: true,
  offBlockTimeEpoch: true,
  takeoffTimeEpoch: true,
  landingTimeEpoch: true,
  onBlockTimeEpoch: true,
  personalRemarks: true,
  personsOnBoard: true,
  picMemberId: true,
  picRole: true,
  privOrComFlight: true,
  status: true,
  totalTimeInService: true,
})

// Regular members cannot edit all fields
export const FlightLogMemberUpsertSchema = FlightLogUpsertSchema.omit({
  ajlbBlankRowsBefore: true,
  ajlbSeqNo: true,
  invoiceNumber: true,
  isBillableFlight: true,
  nonBillingApprovedByMemberId: true,
  nonBillingReason: true,
  status: true,
})

export const FlightLogTimesSchema = z.object({
  offBlockTimeEpoch: bigintAsString,
  takeoffTimeEpoch: bigintAsString,
  landingTimeEpoch: bigintAsString,
  onBlockTimeEpoch: bigintAsString,
})
type FlightLogTimes = z.infer<typeof FlightLogTimesSchema>

export const flightLogDateValidator = <T extends ZodObject<typeof FlightLogTimesSchema.shape>>(
  schema: T,
) =>
  // Zod's refine doesn't work unless all fields are valid.
  // Use preprocessor instead to get error messages shown in the UI with incomplete form.
  // https://github.com/colinhacks/zod/issues/479#issuecomment-2429834215
  z.preprocess((input, ctx) => {
    const parsed = schema
      .pick({
        offBlockTimeEpoch: true,
        takeoffTimeEpoch: true,
        landingTimeEpoch: true,
        onBlockTimeEpoch: true,
      })
      .strip()
      .partial()
      .safeParse(input)

    if (parsed.success) {
      const validate = (
        prevKey: keyof FlightLogTimes,
        nextKey: keyof FlightLogTimes,
        minutes: number,
      ) => {
        if (parsed.data[prevKey] && parsed.data[nextKey]) {
          const prev = Number(parsed.data[prevKey])
          const next = Number(parsed.data[nextKey])

          // check the correct order
          if (next <= prev) {
            ctx.addIssue({
              code: z.ZodIssueCode.too_small,
              minimum: prev,
              inclusive: false,
              message: prev.toString(),
              type: 'bigint',
              path: [nextKey],
            })
          }

          // check limit how long the block can be
          const maximum = prev + minutes * 60
          if (next > maximum) {
            ctx.addIssue({
              code: z.ZodIssueCode.too_big,
              maximum,
              message: maximum.toString(),
              inclusive: true,
              type: 'bigint',
              path: [nextKey],
            })
          }
        }
      }

      // taxi out is limited to 1 hour
      validate('offBlockTimeEpoch', 'takeoffTimeEpoch', 60)

      // flight max 6 hours
      validate('takeoffTimeEpoch', 'landingTimeEpoch', 360)

      // taxi in is limited to 30 minutes
      validate('landingTimeEpoch', 'onBlockTimeEpoch', 30)
    }
    return input
  }, schema)

// Infer the TypeScript type from the Zod schema
export type FlightLog = z.infer<typeof FlightLogSchema>
export type FlightLogUpsertRequest = z.infer<typeof FlightLogUpsertSchema>
export type FlightLogMemberRequest = z.infer<typeof FlightLogMemberUpsertSchema>

export const FlightLogListEntrySchema = FlightLogSchema.pick({
  acTotalFlightTime: true,
  aircraftRegistration: true,
  ajlbBlankRowsBefore: true,
  ajlbSeqNo: true,
  arrivalAirport: true,
  billableMemberId: true,
  blockTime: true,
  crew2LastName: true,
  departureAirport: true,
  flightId: true,
  flightTime: true,
  flightType: true,
  fuelRemainingLitres: true,
  fuelUpliftLitres: true,
  instrumentFlyingMins: true,
  isBillableFlight: true,
  nightFlyingMins: true,
  numberOfLandings: true,
  numberOfNightLandings: true,
  oilUpliftLitres: true,
  offBlockTimeUtc: true,
  takeoffTimeUtc: true,
  landingTimeUtc: true,
  onBlockTimeUtc: true,
  personsOnBoard: true,
  picLastName: true,
  status: true,
  totalTimeInService: true,
})

export type FlightLogListEntry = z.infer<typeof FlightLogListEntrySchema>

export const FlightLogListResponseSchema = z.object({
  logs: z.array(FlightLogListEntrySchema),
  page: z.number().int().optional(),
  limit: z.number().int().optional(),
  pages: z.number().int().optional(),
  rows: z.number().int().optional(),
})

export type FlightLogListResponse = z.infer<typeof FlightLogListResponseSchema>

export const FlightTimeTotalsSchema = z.object({
  acTotalFlightTime: z.string(),
  acTotalFlightHours: z.number(),
  aircraftRegistration: z.string(),
  ajlbSeqNo: z.number().int(),
  flightLogMinsThisAjlb: z.number().int(),
  flightTimeThisAjlb: z.string(),
  totalFlightMinsAtAjlbStart: z.number().int(),
  totalFlightTimeAtAjlbStart: z.string(),
})

export type FlightTimeTotals = z.infer<typeof FlightTimeTotalsSchema>

export const AirfieldListResponseSchema = z.object({
  airfields: z.array(
    z.object({
      ident: z.string(),
      name: z.string(),
      country: z.string(),
    }),
  ),
})

export type AirfieldListResponse = z.infer<typeof AirfieldListResponseSchema>
