import { z, ZodObject } from 'zod'

import { AuditableSchema, BigintAsString, BooleanSchema, UpsertSchema } from '../../types/schema.ts'

export const CrewRoleEnum = z.enum(['FE', 'FI', 'OBS', 'PIC', 'STU'])
export const PrivOrComFlightEnum = z.enum(['P', 'C'])
export type PrivOrComFlight = z.infer<typeof PrivOrComFlightEnum>

export enum FlightLogStatus {
  NEW = 'NEW',
  VALIDATED = 'VALIDATED',
  QUEUED_FOR_INVOICING = 'QUEUED_FOR_INVOICING',
  INVOICED = 'INVOICED',
  PAID = 'PAID',
}

export enum FlightType {
  // currently valid types

  // 1: Harjoituslento
  // 5: Yö harjoituslento
  PRIVATE = 'PRIVATE',

  // 2: 'Koululento',
  // 4: Koulumatkalento
  // 7: Yö Koululento
  // 8: Yö Koulumatkalento
  // 11: Kertauskoululento
  SCHOOL = 'SCHOOL',
  DTO = 'DTO',

  // 16: SAR tehtävä
  // 17: SAR koulutus
  SAR = 'SAR',

  // legacy types
  // 3: Matkalento
  // 6: Yö Matkalento
  XC = 'XC',
  // 9: Välitarkastuslento
  // 10: Tarkastuslento
  CHECKFLIGHT = 'CHECKFLIGHT',
  // 12: Siirtolento
  FERRY = 'FERRY',
  // 13: Taitolento
  AEROBATICS = 'AEROBATICS',
  // 14: Muu (tarkenna huomautuksiin)
  OTHER = 'OTHER',
  // 18: Koelento
  TEST_FLIGHT = 'TEST_FLIGHT',
}

export const FlightLogFiltersSchema = z
  .object({
    flightId: z.string().optional(),
    billableMemberId: z.string().optional(),
    anyCrewMemberId: z.string().optional(),
    aircraftRegistration: z.string().optional(),
    ajlbSeqNo: z.coerce.number().int().optional(),
    pic: z.string().optional(),
    crew2: z.string().optional(),
    crew3: z.string().optional(),
    crew4: z.string().optional(),
    startDate: z.string().datetime().optional(),
    endDate: z.string().datetime().optional(),
    status: z.nativeEnum(FlightLogStatus).optional(),
    page: z.coerce.number().int().optional(),
    limit: z.coerce.number().int().optional(),
    orderLatestFirst: BooleanSchema.optional(),
    incidentsOrObservations: BooleanSchema.optional(),
  })
  .strict()

// Type inference from the schema (should match your interface)
export type FlightLogFilters = z.infer<typeof FlightLogFiltersSchema>

export const FlightLogSchema = AuditableSchema.extend({
  acTotalFlightTime: z.string().nullable().readonly(),
  acTotalLandings: z.number().int().nullable().readonly(),
  aircraftRegistration: z.string(),
  ajlbBlankRowsBefore: z.number().int().min(0),
  ajlbSeqNo: z.number().int().positive(),
  ajlbPageNo: z.number().int().positive(),
  ajlbRowNo: z.number().int().positive().readonly(),
  ajlbTotalLandings: z.number().int().nullable().readonly(),
  arrivalAirport: z.string().min(1),
  billableMemberId: z.string().min(1),
  billingRemarks: z.string().nullable(),
  blockMins: z.number().readonly(),
  blockTime: z.string().readonly(),
  crew2LastName: z.string().nullable().readonly(),
  crew2MemberId: z.string().nullable(),
  crew2Role: CrewRoleEnum.nullable(),
  crew3LastName: z.string().nullable().readonly(),
  crew3MemberId: z.string().nullable(),
  crew3Role: CrewRoleEnum.nullable(),
  crew4LastName: z.string().nullable().readonly(),
  crew4MemberId: z.string().nullable(),
  crew4Role: CrewRoleEnum.nullable(),
  departureAirport: z.string().min(1),
  flightId: z.string().readonly(),
  flightMins: z.number().readonly(),
  flightTime: z.string().readonly(),
  flightType: z.nativeEnum(FlightType),
  fuelRemainingLitres: z.number().positive(),
  fuelUpliftLitres: z.number().min(0).nullable(),
  incidentOrObservations: z.string().nullable(),
  instrumentFlyingMins: z.number().int().min(0),
  invoiceNumber: z.string().nullable(),
  isBillableFlight: z.boolean(),
  isDtoTrainingFlight: z.boolean(),
  isBilled: z.boolean().readonly(),
  partiallyBillableFlight: z.boolean().nullable().default(false),
  entryErrorFee: z.boolean().nullable().default(false),
  entryErrorFeeAppliedByMemberId: z.string().nullable(),
  nightFlyingMins: z.number().int().min(0),
  nonBillingApprovedByMemberId: z.string().nullable(),
  nonBillingReason: z.string().nullable(),
  minBillableExceptionReason: z.string().nullable(),
  minBillableExceptionApprovedByMemberId: z.string().nullable(),
  validationRemarks: z.string().nullable(),
  numberOfLandings: z.number().int().min(1),
  numberOfNightLandings: z.number().int().min(0),
  oilUpliftLitres: z.number().min(0).nullable(),
  offBlockTimeEpoch: BigintAsString,
  offBlockTimeUtc: z.string().datetime().readonly(),
  takeoffTimeEpoch: BigintAsString,
  takeoffTimeUtc: z.string().datetime().readonly(),
  landingTimeEpoch: BigintAsString,
  landingTimeUtc: z.string().datetime().readonly(),
  onBlockTimeEpoch: BigintAsString,
  onBlockTimeUtc: z.string().datetime().readonly(),
  personalRemarks: z.string().nullable(),
  personsOnBoard: z.number().int().min(1).max(4),
  picLastName: z.string().readonly(),
  picMemberId: z.string(),
  picRole: CrewRoleEnum,
  privOrComFlight: PrivOrComFlightEnum,
  status: z.nativeEnum(FlightLogStatus),
  totalTimeInService: z.number().nullable(),
})

// All editable fields which are not generated by the database
export const FlightLogUpsertSchema = UpsertSchema(FlightLogSchema).pick({
  aircraftRegistration: true,
  ajlbBlankRowsBefore: true,
  ajlbSeqNo: true,
  arrivalAirport: true,
  billableMemberId: true,
  billingRemarks: true,
  crew2MemberId: true,
  crew2Role: true,
  crew3MemberId: true,
  crew3Role: true,
  crew4MemberId: true,
  crew4Role: true,
  departureAirport: true,
  flightType: true,
  fuelRemainingLitres: true,
  fuelUpliftLitres: true,
  incidentOrObservations: true,
  instrumentFlyingMins: true,
  isBillableFlight: true,
  nightFlyingMins: true,
  nonBillingReason: true,
  nonBillingApprovedByMemberId: true,
  minBillableExceptionReason: true,
  minBillableExceptionApprovedByMemberId: true,
  partiallyBillableFlight: true,
  entryErrorFee: true,
  entryErrorFeeAppliedByMemberId: true,
  validationRemarks: true,
  numberOfLandings: true,
  numberOfNightLandings: true,
  oilUpliftLitres: true,
  offBlockTimeEpoch: true,
  takeoffTimeEpoch: true,
  landingTimeEpoch: true,
  onBlockTimeEpoch: true,
  personalRemarks: true,
  personsOnBoard: true,
  picMemberId: true,
  picRole: true,
  totalTimeInService: true,
})

// extra raw fields needed for migration
export const FlightLogMigrationSchema = FlightLogSchema.pick({
  isBillableFlight: true,
  isDtoTrainingFlight: true,
  invoiceNumber: true,
}).merge(FlightLogUpsertSchema)

export type FlightLogMigrationRequest = z.infer<typeof FlightLogMigrationSchema>

// Regular members cannot edit all fields
export const FlightLogMemberUpsertSchema = FlightLogUpsertSchema.omit({
  ajlbBlankRowsBefore: true,
  ajlbSeqNo: true,
  billableMemberId: true,
  isBillableFlight: true,
  nonBillingReason: true,
  nonBillingApprovedByMemberId: true,
  minBillableExceptionReason: true,
  minBillableExceptionApprovedByMemberId: true,
  entryErrorFee: true,
  entryErrorFeeAppliedByMemberId: true,
  validationRemarks: true,
})

// Editable fields after validation
export const ValidatedFlightLogAdminUpsertSchema = FlightLogUpsertSchema.pick({
  billableMemberId: true,
  billingRemarks: true,
  isBillableFlight: true,
  nonBillingReason: true,
  nonBillingApprovedByMemberId: true,
  minBillableExceptionReason: true,
  minBillableExceptionApprovedByMemberId: true,
  partiallyBillableFlight: true,
  entryErrorFee: true,
  entryErrorFeeAppliedByMemberId: true,
  validationRemarks: true,
  personalRemarks: true,
})
export const ValidatedFlightLogMemberUpsertSchema = FlightLogUpsertSchema.pick({
  billingRemarks: true,
  personalRemarks: true,
})

// Editable fields after billing
export const BilledFlightLogUpsertSchema = FlightLogUpsertSchema.pick({
  personalRemarks: true,
})

export const FlightLogTimesSchema = z.object({
  offBlockTimeEpoch: BigintAsString,
  takeoffTimeEpoch: BigintAsString,
  landingTimeEpoch: BigintAsString,
  onBlockTimeEpoch: BigintAsString,
})

type FlightLogTimes = z.infer<typeof FlightLogTimesSchema>

export const validateFlightLogTimes = (
  times: Partial<FlightLogTimes>,
  addIssue: (i: z.IssueData) => void,
) => {
  const validate = (
    prevKey: keyof FlightLogTimes,
    nextKey: keyof FlightLogTimes,
    minutes: number,
  ) => {
    if (times[prevKey] && times[nextKey]) {
      const prev = Number(times[prevKey])
      const next = Number(times[nextKey])

      // check the correct order
      if (next <= prev) {
        addIssue({
          code: 'too_small',
          minimum: prev,
          inclusive: false,
          origin: 'number',
          input: next,
          message: prev.toString(),
          path: [nextKey],
        })
      }

      // check limit how long the block can be
      const maximum = prev + minutes * 60
      if (next > maximum) {
        addIssue({
          code: 'too_big',
          maximum,
          inclusive: true,
          origin: 'number',
          input: next,
          message: maximum.toString(),
          path: [nextKey],
        })
      }
    }
  }

  // taxi out is limited to 1 hour
  validate('offBlockTimeEpoch', 'takeoffTimeEpoch', 60)

  // flight max 6 hours
  validate('takeoffTimeEpoch', 'landingTimeEpoch', 360)

  // taxi in is limited to 30 minutes
  validate('landingTimeEpoch', 'onBlockTimeEpoch', 30)

  // None of the times may be in the future — the DB has the same constraint, but
  // checking it here surfaces a friendly validation message at entry time instead of
  // a raw constraint-violation error only on submit.
  const nowEpoch = Math.floor(Date.now() / 1000)
  ;(
    ['offBlockTimeEpoch', 'takeoffTimeEpoch', 'landingTimeEpoch', 'onBlockTimeEpoch'] as const
  ).forEach((key) => {
    const value = times[key]
    if (value == null) return
    const epoch = Number(value)
    if (epoch > nowEpoch) {
      addIssue({
        code: 'too_big',
        maximum: nowEpoch,
        inclusive: true,
        origin: 'number',
        input: epoch,
        // Prefixed so the UI can tell "this is in the future" apart from the
        // duration-limit checks above, which share the same too_big code but should
        // keep showing "must be before HH:mm" instead.
        message: `future:${nowEpoch}`,
        path: [key],
      })
    }
  })
}

export const validateFlightLogBusinessRules = (
  data: Partial<{
    flightType: FlightType
    entryErrorFee: boolean | null
    validationRemarks: string | null
    isBillableFlight: boolean
    nonBillingReason: string | null
    partiallyBillableFlight: boolean | null
    billingRemarks: string | null
  }>,
  addIssue: (i: z.IssueData) => void,
) => {
  if (data.entryErrorFee && !data.validationRemarks?.trim()) {
    addIssue({
      code: 'custom',
      input: data.validationRemarks,
      message: 'Validation remarks are required when entry error fee is applied',
      path: ['validationRemarks'],
    })
  }

  if (data.isBillableFlight === false && !data.nonBillingReason?.trim()) {
    addIssue({
      code: 'custom',
      input: data.nonBillingReason,
      message: 'Non-billing reason is required when flight is marked as non-billable',
      path: ['nonBillingReason'],
    })
  }

  const requiresBillingRemarksByFlightType =
    data.flightType === FlightType.TEST_FLIGHT || data.flightType === FlightType.FERRY

  if (
    (data.partiallyBillableFlight || requiresBillingRemarksByFlightType) &&
    !data.billingRemarks?.trim()
  ) {
    addIssue({
      code: 'custom',
      input: data.billingRemarks,
      message: requiresBillingRemarksByFlightType
        ? 'Billing remarks are required for test and ferry flights'
        : 'Billing remarks are required for partially billable flights',
      path: ['billingRemarks'],
    })
  }

  if (data.partiallyBillableFlight && data.isBillableFlight === false) {
    addIssue({
      code: 'custom',
      input: data.partiallyBillableFlight,
      message: 'A flight cannot be both partially billable and non-billable',
      path: ['partiallyBillableFlight'],
    })
  }

  if (data.isBillableFlight === false && data.entryErrorFee) {
    addIssue({
      code: 'custom',
      input: data.entryErrorFee,
      message: 'A non-billable flight cannot have an entry error fee',
      path: ['entryErrorFee'],
    })
  }
}

export const flightLogDateValidator = <T extends ZodObject<typeof FlightLogTimesSchema.shape>>(
  schema: T,
) =>
  // Zod's refine doesn't work unless all fields are valid.
  // Use preprocessor instead to get error messages shown in the UI with incomplete form.
  // https://github.com/colinhacks/zod/issues/479#issuecomment-2429834215
  z.preprocess((input, ctx) => {
    const parsed = schema
      .pick({
        offBlockTimeEpoch: true,
        takeoffTimeEpoch: true,
        landingTimeEpoch: true,
        onBlockTimeEpoch: true,
      })
      .strip()
      .partial()
      .safeParse(input)

    if (parsed.success) {
      validateFlightLogTimes(parsed.data, ctx.addIssue)
    }
    return input
  }, schema)

// Infer the TypeScript type from the Zod schema
export type FlightLog = z.infer<typeof FlightLogSchema>
export type FlightLogUpsertRequest = z.infer<typeof FlightLogUpsertSchema>
export type FlightLogMemberRequest = z.infer<typeof FlightLogMemberUpsertSchema>

export const FlightLogValidationRequestSchema = z.object({
  revert: z.boolean().optional(),
})

export type FlightLogValidationRequest = z.infer<typeof FlightLogValidationRequestSchema>

export const FlightLogListEntrySchema = FlightLogSchema.pick({
  acTotalFlightTime: true,
  acTotalLandings: true,
  aircraftRegistration: true,
  ajlbBlankRowsBefore: true,
  ajlbSeqNo: true,
  ajlbRowNo: true,
  arrivalAirport: true,
  billableMemberId: true,
  blockMins: true,
  blockTime: true,
  crew2LastName: true,
  departureAirport: true,
  flightId: true,
  flightMins: true,
  flightTime: true,
  flightType: true,
  fuelRemainingLitres: true,
  fuelUpliftLitres: true,
  incidentOrObservations: true,
  instrumentFlyingMins: true,
  isBillableFlight: true,
  isBilled: true,
  invoiceNumber: true,
  minBillableExceptionReason: true,
  nightFlyingMins: true,
  numberOfLandings: true,
  numberOfNightLandings: true,
  oilUpliftLitres: true,
  offBlockTimeUtc: true,
  takeoffTimeUtc: true,
  landingTimeUtc: true,
  onBlockTimeUtc: true,
  personsOnBoard: true,
  picLastName: true,
  status: true,
  totalTimeInService: true,
}).extend({
  acTotalFlightMins: z.number().int().nullable(),
  creditedMins: z.number().int().nullable(),
  estimatedCost: z.number().nullable(),
  isTrainingProgramPilot: z.boolean().nullable(),
})

export type FlightLogListEntry = z.infer<typeof FlightLogListEntrySchema>

// Exact physical-row placement of one own-row (rows > 0) note/defect on the requested
// ajlb page, from flight.vw_ajlb_live_rows -- lets the frontend place these rows
// directly instead of reconstructing page/row layout from flightMins comparisons,
// which could either overflow a page past rowsPerPage or silently drop rows that
// should have carried onto the next page.
export const PageItemRowSchema = z.object({
  rowNumber: z.number().int().positive(),
  itemType: z.enum(['note', 'defect']),
  itemId: z.string(),
  // true for the item's own content row (shows its description); false for a
  // continuation of its own multi-row content or one of its blankRowsAfter spacer
  // rows -- both render identically (blank), so the caller doesn't need to
  // distinguish between them.
  isContentRow: z.boolean(),
})

export type PageItemRow = z.infer<typeof PageItemRowSchema>

export const FlightLogListResponseSchema = z.object({
  logs: z.array(FlightLogListEntrySchema),
  page: z.number().int().optional(),
  limit: z.number().int().optional(),
  pages: z.number().int().optional(),
  rows: z.number().int().optional(),
  pageStartFlightMins: z.number().int().nullable().optional(),
  pageItemRows: z.array(PageItemRowSchema).optional(),
  unbilledEstimatedTotal: z.number().nullable().optional(),
})

export type FlightLogListResponse = z.infer<typeof FlightLogListResponseSchema>

export const FlightTimeTotalsSchema = z.object({
  aircraftRegistration: z.string(),
  ajlbSeqNo: z.number().int(),
  acTotalFlightTime: z.string(),
  acTotalFlightMins: z.number(),
  acTotalLandings: z.number().int().nullable(),
})

export type FlightTimeTotals = z.infer<typeof FlightTimeTotalsSchema>

export const FlightLogStatsFilterSchema = z.object({
  activeOnly: BooleanSchema.optional(),
})
export type FlightLogStatsFilter = z.infer<typeof FlightLogStatsFilterSchema>

export const FlightLogPageForMinsFilterSchema = z.object({
  aircraftRegistration: z.string().min(1),
  ajlbSeqNo: z.coerce.number().int().positive(),
  flightMins: z.coerce.number().int().min(0),
})
export type FlightLogPageForMinsFilter = z.infer<typeof FlightLogPageForMinsFilterSchema>

export const FlightLogStatsSchema = z.object({
  aircraftRegistration: z.string(),
  lastFlightId: z.string().nullable(),
  lastTakeoffTimeUtc: z.string().datetime().nullable(),
  totalLandings: z.number().int(),
  totalFlightMins: z.number().int(),
  landings1month: z.number().int(),
  landings3month: z.number().int(),
  landings6month: z.number().int(),
  landings12month: z.number().int(),
  time1month: z.number().int(),
  time3month: z.number().int(),
  time6month: z.number().int(),
  time12month: z.number().int(),
})

export type FlightLogStats = z.infer<typeof FlightLogStatsSchema>

export const FlightLogStatsResponseSchema = z.object({
  stats: z.array(FlightLogStatsSchema),
})

export type FlightLogStatsResponse = z.infer<typeof FlightLogStatsResponseSchema>

export const FlightLogOverlapQuerySchema = z
  .object({
    aircraftRegistration: z.string().min(1),
    offBlockTimeEpoch: z.coerce.number().int(),
    onBlockTimeEpoch: z.coerce.number().int(),
    // omitted when checking a brand new entry
    excludeFlightId: z.string().optional(),
  })
  .strict()

export type FlightLogOverlapQuery = z.infer<typeof FlightLogOverlapQuerySchema>

export const FlightLogOverlapConflictSchema = z.object({
  flightId: z.string(),
  aircraftRegistration: z.string(),
  offBlockTimeUtc: z.string().datetime(),
  onBlockTimeUtc: z.string().datetime(),
  status: z.nativeEnum(FlightLogStatus),
})

export type FlightLogOverlapConflict = z.infer<typeof FlightLogOverlapConflictSchema>

export const FlightLogOverlapResponseSchema = z.object({
  conflicts: z.array(FlightLogOverlapConflictSchema),
})

export type FlightLogOverlapResponse = z.infer<typeof FlightLogOverlapResponseSchema>

export const AirfieldListResponseSchema = z.object({
  airfields: z.array(
    z.object({
      ident: z.string(),
      name: z.string(),
      country: z.string(),
    }),
  ),
})

export type AirfieldListResponse = z.infer<typeof AirfieldListResponseSchema>

export enum InvoicableFlights {
  FERRY = 'FERRY',
  TEST_FLIGHT = 'TEST_FLIGHT',
  COMMENT = 'COMMENT',
  ENTRY_ERROR = 'ENTRY_ERROR',
  PARTIALLY_BILLABLE = 'PARTIALLY_BILLABLE',
  MIN_BILLABLE = 'MIN_BILLABLE',
  OTHER = 'OTHER',
}

export const InvoicableFlightFiltersSchema = z
  .object({
    aircraftRegistration: z.string().nullable(),
    endDate: z.string().date(),
    flights: z.nativeEnum(InvoicableFlights).optional(),
    page: z.coerce.number().int().optional(),
    limit: z.coerce.number().int().optional(),
  })
  .strict()

export type InvoicableFlightFilters = z.infer<typeof InvoicableFlightFiltersSchema>

export const InvoicableFlightSchema = FlightLogSchema.pick({
  aircraftRegistration: true,
  arrivalAirport: true,
  billableMemberId: true,
  billingRemarks: true,
  departureAirport: true,
  flightId: true,
  flightTime: true,
  flightMins: true,
  blockMins: true,
  blockTime: true,
  flightType: true,
  fuelUpliftLitres: true,
  isBillableFlight: true,
  nonBillingReason: true,
  minBillableExceptionReason: true,
  numberOfLandings: true,
  takeoffTimeUtc: true,
  landingTimeUtc: true,
  personsOnBoard: true,
  picLastName: true,
  status: true,
  validationRemarks: true,
}).extend({
  billableMemberLastName: z.string().nullable().readonly(),
  isTrainingProgramPilot: z.boolean().nullable().readonly(),
  billingId: z.string().nullable().readonly(),
  partiallyBillableFlight: z.boolean().nullable(),
  entryErrorFee: z.boolean().nullable(),
  creditedMins: z.number().int().nullable(),
  creditedNote: z.string().nullable(),
})

export type InvoicableFlight = z.infer<typeof InvoicableFlightSchema>

export const FlightCreditSchema = z.object({
  flightId: z.string(),
  creditedMins: z.number().int().min(1),
  note: z.string().nullable().optional(),
})

export type FlightCredit = z.infer<typeof FlightCreditSchema>

export const FlightInvoicePayloadSchema = z.object({
  flights: z.array(InvoicableFlightSchema),
})

export type FlightInvoicePayload = z.infer<typeof FlightInvoicePayloadSchema>

export const PrepaidFlightUsageSchema = z.object({
  memberPackageId: z.number().int(),
  minutesUsed: z.number().int().nonnegative(),
  perMinRate: z.number().nonnegative(),
  expiresAt: z.string().date(),
  simplbooksItemId: z.string().nullable(),
})

export type PrepaidFlightUsage = z.infer<typeof PrepaidFlightUsageSchema>

export const PrepaidInvoicableFlightSchema = InvoicableFlightSchema.extend({
  billableMinutes: z.number().int().nonnegative(),
  packageEligibleMinutes: z.number().int().nonnegative(),
  availablePrepaidMinutes: z.number().int().nonnegative(),
  prepaidMinutesUsed: z.number().int().nonnegative(),
  standardMinutes: z.number().int().nonnegative(),
  remainingPrepaidMinutes: z.number().int().nonnegative(),
  topUpMins: z.number().int().nonnegative(),
  packageUsages: z.array(PrepaidFlightUsageSchema),
})

export type PrepaidInvoicableFlight = z.infer<typeof PrepaidInvoicableFlightSchema>

export const PrepaidFlightGroupSchema = z.object({
  billableMemberId: z.string(),
  billableMemberLastName: z.string().nullable(),
  aircraftRegistration: z.string(),
  availablePrepaidMinutes: z.number().int().nonnegative(),
  prepaidMinutesUsed: z.number().int().nonnegative(),
  remainingPrepaidMinutes: z.number().int().nonnegative(),
  flights: z.array(PrepaidInvoicableFlightSchema),
})

export type PrepaidFlightGroup = z.infer<typeof PrepaidFlightGroupSchema>

export const PrepaidFlightSummaryResponseSchema = z.object({
  groups: z.array(PrepaidFlightGroupSchema),
})

export type PrepaidFlightSummaryResponse = z.infer<typeof PrepaidFlightSummaryResponseSchema>

export const InvoicableFlightListResponseSchema = z.object({
  logs: z.array(InvoicableFlightSchema),
  page: z.number().int().optional(),
  limit: z.number().int().optional(),
  pages: z.number().int().optional(),
  rows: z.number().int().optional(),
})

export type InvoicableFlightListResponse = z.infer<typeof InvoicableFlightListResponseSchema>

export const InvoiceFlightsSchema = z
  .object({
    aircraftRegistration: z.string(),
    endDate: z.string().date(),
  })
  .strict()

export type InvoiceFlights = z.infer<typeof InvoiceFlightsSchema>

export enum FlightLogExportFormat {
  FOREFLIGHT = 'FOREFLIGHT',
  MYFLIGHTBOOK = 'MYFLIGHTBOOK',
  CREWLOUNGE = 'CREWLOUNGE',
  LOGBOOK_AERO = 'LOGBOOK_AERO',
  LOGTEN = 'LOGTEN',
  FLYLOG = 'FLYLOG',
  CSV = 'CSV',
  EASA_PDF = 'EASA_PDF',
}

export const FlightLogExportFiltersSchema = z
  .object({
    startDate: z.string().datetime().optional(),
    endDate: z.string().datetime().optional(),
    aircraftRegistration: z.string().optional(),
    format: z.nativeEnum(FlightLogExportFormat).optional(),
  })
  .strict()

export type FlightLogExportFilters = z.infer<typeof FlightLogExportFiltersSchema>

export type FlightLogExportEntry = FlightLogListEntry & {
  flightMins: number
  /** Role recorded in crew slot 1 (the `pic_*` columns) — not necessarily the exporting pilot. */
  picRole: string | null
  /** Role the pilot this export is generated for actually flew in, from any crew slot. */
  ownRole: string | null
  /** Last name of the crew member who acted as pilot in command on this flight. */
  actingPicLastName: string
  aircraftModel: string | null
  personalRemarks: string | null
}

export const FlightLogExportCountResponseSchema = z.object({ count: z.number().int() })
export type FlightLogExportCountResponse = z.infer<typeof FlightLogExportCountResponseSchema>
