flyway.url=jdbc:postgresql://localhost:5432/mik_ng
flyway.user=admin
flyway.password=password
flyway.defaultSchema=public
flyway.schemas=member,flight,static,accts,schedule,stats,shop,prepaid,exam,dto,inventory,club,liquid
flyway.validateMigrationNaming=true
flyway.cleanDisabled=false
flyway.placeholders.app_db_user=mik_app_test
flyway.placeholders.mik_db_name=mik_ng
