flyway.defaultSchema=public
flyway.schemas=member,flight,static,accts,schedule,stats,shop,prepaid,exam,dto
flyway.validateMigrationNaming=true
flyway.cleanDisabled=true
flyway.placeholders.app_db_user=mik_app_prod
flyway.placeholders.mik_db_name=mik_ng_prod
