flyway.url=jdbc:postgresql://localhost:5432/mik_ng
flyway.user=admin
flyway.password=password
flyway.defaultSchema=public
flyway.schemas=member,flight
flyway.locations=filesystem:./schema/testdata
flyway.validateMigrationNaming=true
flyway.cleanDisabled=false
flyway.table=flyway_data_history
flyway.baselineOnMigrate=true
flyway.baselineVersion=0