name: Postgres DB Backup to Cloudflare R2

on:
    schedule:
        - cron: "0 1 * * 0" # At 01:00 on Sunday
    workflow_dispatch:

jobs:
    backup:
        runs-on: ubuntu-latest
        env:
            DO_POSTGRES_USER: ${{ vars.DO_POSTGRES_USER }}
            DO_POSTGRES_PASSWORD: ${{ secrets.DO_POSTGRES_PASSWORD }}
            DO_POSTGRES_URL: ${{ vars.DO_POSTGRES_URL }}
            CLOUDFLARE_R2_ACCESSKEY_ID: ${{ secrets.CLOUDFLARE_R2_ACCESSKEY_ID }}
            CLOUDFLARE_R2_SECRET_ACCESSKEY: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESSKEY }}
            CLOUDFLARE_R2_EU_ENDPOINT: ${{ vars.CLOUDFLARE_R2_EU_ENDPOINT }}
            CLOUDFLARE_R2_BUCKET_NAME_DB_BACKUP: ${{ vars.CLOUDFLARE_R2_BUCKET_NAME_DB_BACKUP }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install PostgreSQL 17 client
              run: |
                  sudo apt-get update
                  sudo apt-get install -y wget gnupg2
                  echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
                  wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
                  sudo apt-get update
                  sudo apt-get install -y postgresql-client-17

            - name: Dump PostgreSQL database
              run: |
                  export PGPASSWORD="$DO_POSTGRES_PASSWORD"
                  export PGUSER="$DO_POSTGRES_USER"
                  export PGHOST=$(echo $DO_POSTGRES_URL | sed -E 's#^([^:/]+)(:[0-9]+)?/.*$#\1#')
                  export PGPORT=$(echo $DO_POSTGRES_URL | grep -oE ':[0-9]+' | tr -d ':')
                  export PGDATABASE=$(echo $DO_POSTGRES_URL | sed -E 's#.*/##')
                  CONNECTION_STRING="postgresql://$PGUSER:$PGPASSWORD@$PGHOST:$PGPORT/$PGDATABASE"
                  mkdir -p dbbackup
                  BACKUP_FILE="backup-$(date +'%Y-%m-%d-%H%M%S').dump"
                  pg_dump --no-owner --no-privileges --format=custom --file="dbbackup/$BACKUP_FILE" "$CONNECTION_STRING"
                  # Encrypt the backup file
                  openssl enc -aes-256-cbc -salt -pbkdf2 -in dbbackup/$BACKUP_FILE -out dbbackup/${BACKUP_FILE}.enc -pass pass:${{ secrets.BACKUP_ENCRYPTION_PASSWORD }}
                  rm dbbackup/$BACKUP_FILE
            - name: Upload to Cloudflare R2
              uses: jakejarvis/s3-sync-action@master
              with:
                  args: --acl private --follow-symlinks
              env:
                  AWS_S3_BUCKET: ${{ env.CLOUDFLARE_R2_BUCKET_NAME_DB_BACKUP }}
                  AWS_ACCESS_KEY_ID: ${{ env.CLOUDFLARE_R2_ACCESSKEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ env.CLOUDFLARE_R2_SECRET_ACCESSKEY }}
                  AWS_S3_ENDPOINT: ${{ env.CLOUDFLARE_R2_EU_ENDPOINT }}
                  AWS_REGION: "auto"
                  SOURCE_DIR: dbbackup/
                  DEST_DIR: /

            # Optional: Clean up R2 bucket by removing files not in /dbbackup
            # - name: Remove files not in /dbbackup from R2
            #   run: |
            #       echo "AWS_S3_BUCKET is: $AWS_S3_BUCKET"
            #       printenv | grep AWS
            #       aws s3api list-objects-v2 \
            #       --bucket "$AWS_S3_BUCKET" \
            #       --endpoint-url "$AWS_S3_ENDPOINT" \
            #       --query 'Contents[?!(starts_with(Key, `dbbackup/`))].Key' \
            #       --output text | tr '\t' '\n' | while read key; do
            #       if [ -n "$key" ]; then
            #         echo "Deleting $key from R2 bucket $AWS_S3_BUCKET"
            #         aws s3 rm "s3://$AWS_S3_BUCKET/$key" --endpoint-url "$AWS_S3_ENDPOINT"
            #       fi
            #       done
            #   env:
            #       AWS_ACCESS_KEY_ID: ${{ env.CLOUDFLARE_R2_ACCESSKEY_ID }}
            #       AWS_SECRET_ACCESS_KEY: ${{ env.CLOUDFLARE_R2_SECRET_ACCESSKEY }}
            #       AWS_S3_BUCKET: ${{ env.CLOUDFLARE_R2_BUCKET_NAME_DB_BACKUP }}
            #       AWS_S3_ENDPOINT: ${{ env.CLOUDFLARE_R2_EU_ENDPOINT }}
            #       AWS_REGION: "auto"
