name: Intra API Build and Push Docker Image to DO

on:
  push:
    branches: [test] # Adjust branch names as needed

    paths:
      - 'apps/**' # Only trigger if changes are in apps/frontend
      - '.github/workflows/**' # or in the workflows
      - '.do/**' # or in digital ocean yaml
      - 'sql/schema/**' # or in sql files
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check changed paths
        id: paths
        run: |
          git fetch origin ${{ github.event.before }}
          CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "CHANGED=$CHANGED"

          backend_changed=false
          sql_changed=false

          while IFS= read -r path; do
            if [[ "$path" =~ ^apps/backend/ ]]; then
              backend_changed=true
            fi
            if [[ "$path" =~ ^sql/schema/ ]]; then
              sql_changed=true
            fi
          done <<< "$CHANGED"

          echo "backend_changed=$backend_changed" >> $GITHUB_ENV
          echo "sql_changed=$sql_changed" >> $GITHUB_ENV

      - name: Set repo name lowercase
        run: echo "REPO_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Set up doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_TEST_API_KEY }}

      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 1200

      - name: Set environment variables
        run: |
          echo "DATABASE_URL=${{ secrets.POSTGRES_DO_TEST_DB }}" >> $GITHUB_ENV
          echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" >> $GITHUB_ENV
          echo "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}" >> $GITHUB_ENV
          echo "MAGIC_LINK_SECRET=${{ secrets.MAGIC_LINK_SECRET }}" >> $GITHUB_ENV
          echo "REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}" >> $GITHUB_ENV
          echo "ACCESS_TOKEN_EXPIRATION=15 mins" >> $GITHUB_ENV
          echo "REFRESH_TOKEN_EXPIRATION=365 days" >> $GITHUB_ENV
          echo "SMTP_LOGIN=${{ vars.SMTP_LOGIN }}" >> $GITHUB_ENV
          echo "PUBLIC_URL=${{ vars.PUBLIC_URL }}" >> $GITHUB_ENV
          echo "VITE_API_TARGET=${{ vars.VITE_API_TARGET }}" >> $GITHUB_ENV
          echo "BETTERSTACK_API_TOKEN=${{ secrets.BETTERSTACK_API_TOKEN }}" >> $GITHUB_ENV
          echo "SIMPLBOOKS_OUTBOX_WORKER_ENABLED=${{ vars.SIMPLBOOKS_OUTBOX_WORKER_ENABLED }}" >> $GITHUB_ENV

      - name: Build and push Docker image
        if: env.backend_changed == 'true'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: registry.digitalocean.com/mik-ng2/${{ env.REPO_NAME }}:latest

      - name: Run Flyway migrations
        if: env.sql_changed == 'true'
        run: |
          docker run --network host --rm \
            -v ${{ github.workspace }}/sql/schema/migration:/flyway/sql \
            -v ${{ github.workspace }}/sql/migration.conf:/flyway/conf/flyway.conf \
            -e FLYWAY_USER=${{ vars.DO_POSTGRES_USER }} \
            -e FLYWAY_PASSWORD=${{ secrets.DO_POSTGRES_PASSWORD }} \
            -e FLYWAY_URL=jdbc:postgresql://${{ vars.DO_POSTGRES_URL}} \
            flyway/flyway:latest clean migrate

      - name: Run Flyway test data
        if: env.sql_changed == 'true'
        run: |
          docker run --network host --rm \
            -v ${{ github.workspace }}/sql/schema/testdata/:/flyway/sql \
            -v ${{ github.workspace }}/sql/testdata.conf:/flyway/conf/flyway.conf \
            -e FLYWAY_USER=${{ vars.DO_POSTGRES_USER }} \
            -e FLYWAY_PASSWORD=${{ secrets.DO_POSTGRES_PASSWORD }} \
            -e FLYWAY_URL=jdbc:postgresql://${{ vars.DO_POSTGRES_URL}} \
            flyway/flyway:latest migrate

      - name: Replace placeholders in mik-intranet.yaml
        run: |
          envsubst < .do/mik-intranet.yaml > .do/mik-intranet.yaml.temp && mv .do/mik-intranet.yaml.temp .do/mik-intranet.yaml

      - name: Update app on DigitalOcean
        run: doctl apps update ${{ vars.DIGITALOCEAN_BACKEND_APP_ID }} --update-sources --spec .do/mik-intranet.yaml --wait
