# name: Build and Push Front End to Digital Ocean

# on:
#   push:
#     branches: [test]
#     paths:
#       - 'apps/frontend/**' # Only trigger if changes are in apps/frontend
#       - '.github/workflows/**' # or in the workflows
#       - '.do/**' # or in digital ocean yaml

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       # Set up Node.js
#       # - name: Set up Node.js
#       #   uses: actions/setup-node@v4
#       #   with:
#       #     node-version: '23'

#       # Install pnpm
#       #- name: Install pnpm
#       #  run: npm install -g pnpm

#       # Set up doctl (DigitalOcean CLI) using the API key stored in GitHub Secrets
#       - name: Set up doctl
#         uses: digitalocean/action-doctl@v2
#         with:
#           token: ${{ secrets.DIGITAL_OCEAN_TEST_API_KEY }}

#       # Let's set the env vars we need for the DO app
#       - name: Setup env vars for Digital Ocean App
#         run: |
#           echo "VITE_API_TARGET=${{ vars.VITE_API_TARGET }}" >> $GITHUB_ENV

#       # Now we use good 'ol envsubst to substitue the env vars from above into the mik-intra-frontend.yaml file
#       - name: Replace placeholders in mik-intra-frontend.yaml
#         run: |
#           envsubst < .do/mik-intra-frontend.yaml > .do/mik-intra-frontend.yaml.temp && mv .do/mik-intra-frontend.yaml.temp .do/mik-intra-frontend.yaml

#       # Deploy to DigitalOcean App Platform using mik-intra-frontend.yml
#       - name: Deploy App
#         run: doctl apps update ${{ vars.DIGITALOCEAN_BACKEND_APP_ID }} --spec .do/mik-intranet.yaml --wait
#         env:
#           DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITAL_OCEAN_TEST_API_KEY }}
